// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#ifndef _METRIC_ENGINE_HPP
#define _METRIC_ENGINE_HPP

#include "benchmarks/report.hpp"
#include "core/concepts.hpp"
#include "core/errors.hpp"
#include "core/metric_space.hpp"
#include "core/metric_traits.hpp"
#include "core/neighbor.hpp"
#include "core/parameters.hpp"
#include "record.hpp"
#include "core/result.hpp"
#include "core/version.hpp"
#include "stats/correlate/compare.hpp"
#include "modify/dynamics/finite_dynamics.hpp"
#include "modify/represent/represent.hpp"
#include "modify/reduce/compress.hpp"
#include "modify/expand/expand.hpp"
#include "modify/expand/generated.hpp"
#include "modify/resample/denoise.hpp"
#include "stats/properties/describe.hpp"
#include "modify/map/embed.hpp"
#include "stats/structural_analysis/groups.hpp"
#include "modify/map/map.hpp"
#include "stats/search/neighbors.hpp"
#include "stats/structural_analysis/outliers.hpp"
#include "modify/map/reduce.hpp"
#include "space/select/representatives.hpp"
#include "modify/map/clustered_space.hpp"
#include "modify/map/diagnostics.hpp"
#include "modify/map/koc.hpp"
#include "modify/map/mapping.hpp"
#include "modify/map/native_autoencoder.hpp"
#include "modify/map/native_phate_autoencoder.hpp"
#include "modify/map/pcfa.hpp"
#include "stats/structural_analysis/clustering.hpp"
#include "stats/correlate/correlation.hpp"
#include "stats/search/nearest.hpp"
#include "space/index/sparsify.hpp"
#include "modify/compose/native_phate_autoencoder.hpp"
#include "space/storage/cover_tree_index.hpp"
#include "space/storage/diagnostics.hpp"
#include "space/storage/distance_matrix.hpp"
#include "space/storage/graph_topology.hpp"
#include "space/storage/implicit.hpp"
#include "space/storage/knn_graph_index.hpp"
#include "space/storage/distance_table.hpp"
#include "space/storage/strategy.hpp"
#include "space/storage/cache.hpp"
#include "space/storage/execution.hpp"
#include "space/storage/policy.hpp"
#include "stats/structural_analysis/options.hpp"
#include "stats/correlate/options.hpp"
#include "modify/map/options.hpp"
#include "space/storage/representation_options.hpp"
#include "space/select/options.hpp"
#include "stats/search/options.hpp"

#endif
