"""Finite metric-space helpers for the revived Python API."""

from collections.abc import Mapping
import copy as _copy
import math
import numbers
import operator

from metric.exceptions import (
    AmbiguousIntentError,
    IncompatibleSpaceError,
    MetricContractError,
    MetricInputError,
    MissingMetricError,
    StaleRepresentationError,
    StrategyUnavailableError,
)
from metric.runtime import CachePolicy, require_exact_runtime


_VALIDATION_MODES = {"none", "sample", "strict"}
_MATERIALIZED_CACHE_MODES = {"auto", "materialized"}


class RecordId(int):
    """Default stable record identifier generated by Space."""

    def __new__(cls, value):
        return int.__new__(cls, value)


class _EuclideanVectorMetric:
    name = "Euclidean"

    def __call__(self, lhs, rhs):
        lhs_values = self._values(lhs)
        rhs_values = self._values(rhs)
        if len(lhs_values) != len(rhs_values):
            raise MetricInputError("vector records must have the same length")

        total = 0.0
        for lhs_value, rhs_value in zip(lhs_values, rhs_values):
            try:
                delta = float(lhs_value) - float(rhs_value)
            except (TypeError, ValueError):
                raise MetricInputError("vector records must contain numeric values") from None
            total += delta * delta
        return math.sqrt(total)

    def __repr__(self):
        return "Euclidean()"

    @staticmethod
    def _values(record):
        try:
            return list(record)
        except TypeError:
            raise MetricInputError("vector records must be one-dimensional sequences") from None


def _coerce_non_negative_integer(value, name):
    try:
        value = operator.index(value)
    except TypeError:
        raise TypeError(f"{name} must be an integer") from None
    if value < 0:
        raise ValueError(f"{name} must be non-negative")
    return value


def _normalize_validation(validate):
    if not isinstance(validate, str):
        raise TypeError("validate must be a string")
    if validate not in _VALIDATION_MODES:
        raise ValueError(f"validate must be one of {sorted(_VALIDATION_MODES)!r}")
    return validate


def _normalize_cache(cache):
    return cache if isinstance(cache, CachePolicy) else CachePolicy(cache)


def _validate_distance_value(value, lhs_index, rhs_index):
    if isinstance(value, bool) or not isinstance(value, numbers.Real):
        raise MetricContractError(
            f"metric distance for records {lhs_index} and {rhs_index} must be a real number"
        )
    if not math.isfinite(value):
        raise MetricContractError(
            f"metric distance for records {lhs_index} and {rhs_index} must be finite"
        )
    if value < 0:
        raise MetricContractError(
            f"metric distance for records {lhs_index} and {rhs_index} must be non-negative"
        )
    return value


class FiniteMetricSpace:
    """Explicit finite metric space backed by a pairwise distance matrix."""

    def __init__(
        self,
        records,
        metric=None,
        source_space=None,
        representation="metric_space",
        ids=None,
        name=None,
        metadata=None,
        validate="sample",
        copy=False,
        cache="auto",
    ):
        if metric is None:
            raise MissingMetricError(
                "Space requires an explicit metric for arbitrary records. "
                "Use Space(records, metric=Edit()) or another callable metric."
            )
        validate = _normalize_validation(validate)
        cache = _normalize_cache(cache)
        if not isinstance(copy, bool):
            raise TypeError("copy must be a bool")
        self.records = [_copy.copy(record) for record in records] if copy else list(records)
        self.ids = [RecordId(index) for index in range(len(self.records))] if ids is None else list(ids)
        if len(self.ids) != len(self.records):
            raise ValueError("ids must have the same length as records")
        if len(set(self.ids)) != len(self.ids):
            raise ValueError("ids must be unique")
        self._id_to_index = {record_id: index for index, record_id in enumerate(self.ids)}
        self.metric = metric
        self.name = name
        self.metadata = {} if metadata is None else dict(metadata)
        self.source_space = source_space
        self.source_version = source_space.version() if source_space is not None else None
        self.representation = representation
        self.validate = validate
        self.cache = cache
        self._version = 0
        self._lazy_distances = {}
        self._distances = None
        if cache.mode in _MATERIALIZED_CACHE_MODES:
            self._distances = [
                [self._compute_distance(lhs_index, rhs_index) for rhs_index in range(len(self.records))]
                for lhs_index in range(len(self.records))
            ]
        elif validate == "strict":
            self._validate_all_distances()
        else:
            self._validate_sample_distances()

    def __len__(self):
        return len(self.records)

    def __repr__(self):
        record_type = type(self.records[0]).__name__ if self.records else "empty"
        return (
            f"{type(self).__name__}(size={len(self)}, "
            f"metric={self.metric!r}, records={record_type}, name={self.name!r})"
        )

    def __getitem__(self, index):
        return self.records[index]

    def __call__(self, lhs_index, rhs_index):
        return self.distance(lhs_index, rhs_index)

    @classmethod
    def vectors(cls, records, metric=None, **kwargs):
        """Construct a finite metric space from vector records.

        Defaults to a pure Python Euclidean metric so the convenience remains
        available in the core wheel without optional standard-distance bindings.
        """

        return cls(
            records,
            metric=_EuclideanVectorMetric() if metric is None else metric,
            **kwargs,
        )

    @classmethod
    def from_dataframe(cls, dataframe, metric=None, id_column=None, **kwargs):
        if metric is None:
            raise MissingMetricError(
                "Space.from_dataframe requires an explicit metric. "
                "Use Space.from_dataframe(df, metric=callable)."
            )
        if id_column is not None and "ids" in kwargs:
            raise ValueError("use either id_column or ids, not both")
        if not hasattr(dataframe, "to_dict"):
            raise TypeError("dataframe must provide to_dict('records')")

        try:
            rows = dataframe.to_dict("records")
        except TypeError:
            rows = dataframe.to_dict(orient="records")

        ids = None
        records = list(rows)
        if id_column is not None:
            ids = []
            feature_records = []
            for row in records:
                if not isinstance(row, Mapping):
                    raise TypeError("dataframe records must be mappings when id_column is used")
                if id_column not in row:
                    raise KeyError(f"id_column {id_column!r} is not present in every row")
                ids.append(row[id_column])
                feature_records.append({
                    column: value
                    for column, value in row.items()
                    if column != id_column
                })
            records = feature_records

        return cls(records, metric=metric, ids=ids, **kwargs)

    def version(self):
        return self._version

    def touch(self):
        self._version += 1
        return self._version

    def is_stale(self):
        return self.source_space is not None and self.source_space.version() != self.source_version

    def ensure_fresh(self):
        if self.is_stale():
            raise StaleRepresentationError(
                f"{self.representation} representation is stale: source version {self.source_space.version()} "
                f"does not match representation version {self.source_version}. "
                "Rebuild the representation from the source space."
            )
        return self

    def distance(self, lhs_index, rhs_index):
        self.ensure_fresh()
        if self._distances is not None:
            return self._distances[lhs_index][rhs_index]
        if self.cache.mode == "lazy":
            key = (lhs_index, rhs_index)
            if key not in self._lazy_distances:
                self._lazy_distances[key] = self._compute_distance(lhs_index, rhs_index)
            return self._lazy_distances[key]
        return self._compute_distance(lhs_index, rhs_index)

    def record(self, record_id):
        return self.records[self._id_to_index[record_id]]

    def pairwise_distances(self):
        self.ensure_fresh()
        if self._distances is not None:
            return [row[:] for row in self._distances]
        return [
            [self.distance(lhs_index, rhs_index) for rhs_index in range(len(self.records))]
            for lhs_index in range(len(self.records))
        ]

    def pairwise(self, ids=None):
        self.ensure_fresh()
        if ids is None:
            return self.pairwise_distances()

        positions = [self._id_to_index[record_id] for record_id in ids]
        return [
            [self.distance(lhs, rhs) for rhs in positions]
            for lhs in positions
        ]

    def to_matrix(self):
        return FiniteMetricSpace(
            self.records,
            self.metric,
            source_space=self,
            representation="matrix",
            ids=self.ids,
            name=self.name,
            metadata=self.metadata,
            validate=self.validate,
            cache="materialized",
        )

    def to_tree(self):
        from metric.representations import TreeIndex

        return TreeIndex(self)

    def to_graph(self, count):
        from metric.representations import GraphIndex

        return GraphIndex(self, count)

    def knn(self, query, k=1):
        self.ensure_fresh()
        k = _coerce_non_negative_integer(k, "k")
        distances = [
            (index, self.metric(record, query))
            for index, record in enumerate(self.records)
        ]
        return sorted(distances, key=lambda item: item[1])[:k]

    def nn(self, query):
        return self.knn(query, 1)[0]

    def rnn(self, query, radius):
        return [
            (index, distance)
            for index, distance in self.knn(query, len(self.records))
            if distance <= radius
        ]

    def neighbors(self, query, k=None, count=None, radius=None):
        if k is not None and count is not None:
            raise ValueError("use either k or count, not both")
        if radius is not None:
            if k is not None or count is not None:
                raise ValueError("radius cannot be combined with k or count")
            return self.rnn(query, radius)
        value = 1 if k is None and count is None else count if count is not None else k
        return self.knn(query, _coerce_non_negative_integer(value, "count"))

    def _compute_distance(self, lhs_index, rhs_index):
        value = self.metric(self.records[lhs_index], self.records[rhs_index])
        if self.validate != "none":
            _validate_distance_value(value, lhs_index, rhs_index)
        return value

    def _validate_sample_distances(self):
        if self.validate == "none" or not self.records:
            return
        sample_size = min(len(self.records), 3)
        for lhs_index in range(sample_size):
            for rhs_index in range(sample_size):
                self._compute_distance(lhs_index, rhs_index)

    def _validate_all_distances(self):
        for lhs_index in range(len(self.records)):
            for rhs_index in range(len(self.records)):
                self._compute_distance(lhs_index, rhs_index)


class Space(FiniteMetricSpace):
    """Intent-first facade for a finite metric space.

    The revived Python engine facade starts from operations backed by stable
    strategy and result contracts. Learned embedding paths stay out of the core
    facade until they have deterministic coverage.
    """

    def _neighbor_count(self, k=None, count=None):
        if k is not None and count is not None:
            raise ValueError("use either k or count, not both")
        value = 1 if k is None and count is None else count if count is not None else k
        return _coerce_non_negative_integer(value, "count")

    def _neighbor_row(self, source_index, count=None, radius=None, include_self=False):
        self.ensure_fresh()
        neighbors = []
        for candidate_index in range(len(self.records)):
            if not include_self and candidate_index == source_index:
                continue
            distance = self.distance(candidate_index, source_index)
            if radius is None or distance <= radius:
                neighbors.append((candidate_index, distance))
        neighbors.sort(key=lambda item: item[1])
        if count is not None:
            neighbors = neighbors[:count]
        return neighbors

    def neighbors(
        self,
        query=None,
        k=None,
        count=None,
        radius=None,
        *,
        include_self=False,
        strategy=None,
        representation=None,
        runtime=None,
    ):
        from metric.operators import neighbor_result

        runtime_policy = require_exact_runtime(runtime)
        if strategy is not None:
            raise ValueError("strategy overrides are not promoted for Python neighbors yet")

        has_explicit_count = k is not None or count is not None
        neighbor_count = self._neighbor_count(k, count) if has_explicit_count or radius is None else None
        if representation is None:
            representation = self._runtime_neighbor_representation(
                runtime_policy,
                query=query,
                count=neighbor_count,
                radius=radius,
                include_self=include_self,
            )
        if query is not None and representation is not None:
            return neighbor_result(
                self.records,
                query=query,
                neighbors=representation.neighbors(query, k=k, count=count, radius=radius),
                representation=getattr(representation, "representation", "metric_space"),
            )
        if representation is not None:
            representation.ensure_fresh()
            if getattr(representation, "representation", None) == "exact_knn_graph":
                rows = [
                    list(representation.neighbors(source_index))[:neighbor_count]
                    for source_index in range(len(self.records))
                ]
                return neighbor_result(
                    self.records,
                    rows=rows,
                    representation=representation.representation,
                )

        if query is None:
            rows = [
                self._neighbor_row(source_index, neighbor_count, radius=radius, include_self=include_self)
                for source_index in range(len(self.records))
            ]
            return neighbor_result(self.records, rows=rows)

        if radius is not None:
            neighbors = self.rnn(query, radius)
            return neighbor_result(
                self.records,
                query=query,
                neighbors=neighbors if neighbor_count is None else neighbors[:neighbor_count],
            )
        return neighbor_result(self.records, query=query, neighbors=self.knn(query, neighbor_count))

    def nearest(self, query):
        return self.neighbors(query, count=1).neighbors[0]

    def within_radius(self, query, radius):
        return self.neighbors(query, radius=radius)

    def groups(self, strategy=None, *, count="auto", radius=None, min_size=1, representation=None, runtime=None):
        runtime_policy = require_exact_runtime(runtime)
        representation_name = self._representation_name(representation)
        if representation is None and runtime_policy.cache_mode == "materialized":
            representation_name = "matrix"
        if strategy is not None and (count != "auto" or radius is not None):
            raise ValueError("use either strategy or count/radius, not both")

        from metric.operators import find_groups
        from metric.strategies import DBSCAN, KMedoids

        if strategy is None:
            if radius is not None:
                strategy = DBSCAN(radius=radius, min_points=min_size)
            else:
                if count == "auto":
                    count = 1 if len(self.records) <= 2 else 2
                strategy = KMedoids(groups=count)

        return find_groups(self.records, self.metric, strategy, representation=representation_name)

    def _nearest_other_distance(self, source_index):
        candidates = [
            self.distance(source_index, candidate_index)
            for candidate_index in range(len(self.records))
            if candidate_index != source_index
        ]
        return min(candidates) if candidates else 0

    def _outlier_count(self, count=None, fraction=0.05):
        if count is not None:
            return _coerce_non_negative_integer(count, "count")
        if fraction < 0 or fraction > 1:
            raise ValueError("fraction must be between 0 and 1")
        if not self.records or fraction == 0:
            return 0
        return max(1, math.ceil(len(self.records) * fraction))

    def outliers(
        self,
        strategy=None,
        *,
        count=None,
        fraction=0.05,
        threshold=None,
        representation=None,
        runtime=None,
    ):
        require_exact_runtime(runtime)
        representation_name = self._representation_name(representation)
        from metric.operators import find_outliers

        if strategy is not None:
            if count is not None or threshold is not None or fraction != 0.05:
                raise ValueError("use either strategy or count/fraction/threshold, not both")
            return find_outliers(self.records, self.metric, strategy, representation=representation_name)

        from metric.operators import Outlier, OutlierResult

        self.ensure_fresh()
        scored = [
            Outlier(record_id=record_index, score=self._nearest_other_distance(record_index))
            for record_index in range(len(self.records))
        ]
        if threshold is not None:
            scored = [outlier for outlier in scored if outlier.score >= threshold]
        scored.sort(key=lambda outlier: outlier.record_id)
        scored.sort(key=lambda outlier: outlier.score, reverse=True)
        if threshold is None:
            scored = scored[:self._outlier_count(count=count, fraction=fraction)]

        return OutlierResult(
            outliers=tuple(scored),
            record_count=len(self.records),
            cluster_count=0,
            noise_count=len(scored),
            exact=True,
            operator_name="find_outliers",
            strategy="nearest_neighbor_distance",
            representation=representation_name,
        )

    def denoise(
        self,
        strategy=None,
        *,
        count=None,
        fraction=0.05,
        threshold=None,
        strength="auto",
        representation=None,
        runtime=None,
    ):
        require_exact_runtime(runtime)
        representation_name = self._representation_name(representation)
        from metric.operators import denoise_space

        if strategy is not None:
            if count is not None or threshold is not None or fraction != 0.05 or strength != "auto":
                raise ValueError("use either strategy or count/fraction/threshold/strength, not both")
            return denoise_space(self.records, self.metric, strategy, representation=representation_name)

        if strength != "auto":
            if count is not None or threshold is not None or fraction != 0.05:
                raise ValueError("strength cannot be combined with count, fraction, or threshold")
            try:
                fraction = float(strength)
            except (TypeError, ValueError):
                raise ValueError("strength must be 'auto' or a fraction between 0 and 1") from None

        from metric.operators import MappingResult

        outlier_ids = {
            outlier.record_id
            for outlier in self.outliers(count=count, fraction=fraction, threshold=threshold).outliers
        }
        kept_record_ids = tuple(
            record_index
            for record_index in range(len(self.records))
            if record_index not in outlier_ids
        )
        denoised_records = [self.records[index] for index in kept_record_ids]

        return MappingResult(
            space=Space(denoised_records, self.metric),
            source_record_ids=kept_record_ids,
            source_record_count=len(self.records),
            target_record_count=len(denoised_records),
            exact=True,
            operator_name="denoise",
            mapping="nearest_neighbor_outlier_filter",
            strategy="nearest_neighbor_distance",
            representation=representation_name,
            inverse_supported=False,
        )

    def representatives(self, k=None, strategy=None, *, count=None, representation=None, runtime=None):
        require_exact_runtime(runtime)
        from metric.operators import find_representatives

        return find_representatives(
            self.records,
            self.metric,
            k,
            strategy=strategy,
            count=count,
            representation=self._representation_name(representation),
        )

    def _representation_name(self, representation):
        representation_name = "metric_space"
        if representation is not None:
            representation.ensure_fresh()
            representation_name = getattr(representation, "representation", representation_name)
        return representation_name

    def _runtime_neighbor_representation(
        self,
        runtime_policy,
        *,
        query,
        count,
        radius,
        include_self,
    ):
        if runtime_policy.representation == "auto":
            if runtime_policy.cache_mode == "materialized":
                return self.to_matrix()
            return None
        if runtime_policy.representation == "metric_space":
            return None
        if runtime_policy.representation == "matrix":
            return self.to_matrix()
        if runtime_policy.representation == "tree":
            return self.to_tree()
        if runtime_policy.representation == "graph":
            if query is not None:
                raise StrategyUnavailableError(
                    "graph runtime representation requires queryless Space.neighbors(...) "
                    "in the Python facade"
                )
            if radius is not None:
                raise StrategyUnavailableError(
                    "graph runtime representation does not support radius neighbor queries "
                    "in the Python facade"
                )
            if include_self:
                raise StrategyUnavailableError(
                    "graph runtime representation does not support include_self=True "
                    "in the Python facade"
                )
            graph_count = (
                runtime_policy.graph_count
                if runtime_policy.graph_count is not None
                else count
            )
            return self.to_graph(count=0 if graph_count is None else graph_count)
        return None

    def reduce(self, count=None, strategy=None, *, representation=None, runtime=None):
        require_exact_runtime(runtime)
        from metric.operators import reduce_space

        return reduce_space(
            self.records,
            self.metric,
            count,
            strategy=strategy,
            representation=self._representation_name(representation),
        )

    def compress(self, count=None, strategy=None, *, representation=None, runtime=None):
        require_exact_runtime(runtime)
        from metric.operators import compress_space

        return compress_space(
            self.records,
            self.metric,
            count,
            strategy=strategy,
            representation=self._representation_name(representation),
        )

    def map(self, transform=None, metric=None, *, target=None, strategy=None, representation=None, runtime=None):
        require_exact_runtime(runtime)
        if transform is None and target is None:
            raise AmbiguousIntentError("Space.map requires transform=... or target=...")
        if transform is not None and target is not None:
            raise AmbiguousIntentError("Space.map uses either transform or target, not both")
        if strategy is not None:
            raise StrategyUnavailableError(
                "Space.map strategy mappings are not promoted yet. "
                "Use transform=... with metric=... for deterministic maps."
            )
        if target is not None:
            raise StrategyUnavailableError(
                "Space.map target mappings are not promoted yet. "
                "Use transform=... with metric=... for deterministic maps."
            )

        from metric.operators import map_space

        return map_space(
            self.records,
            transform,
            self.metric if metric is None else metric,
            representation=self._representation_name(representation),
        )

    def embed(self, dimensions=2, strategy=None, *, representation=None, runtime=None):
        require_exact_runtime(runtime)
        representation_name = self._representation_name(representation)

        from metric.operators import embed_space

        return embed_space(
            self.records,
            self.metric,
            dimensions=dimensions,
            strategy=strategy,
            representation=representation_name,
        )

    def describe(self, *, representation=None, runtime=None):
        require_exact_runtime(runtime)
        representation_name = self._representation_name(representation)

        from metric.operators import describe_structure

        return describe_structure(self.records, self.metric, representation=representation_name)

    def describe_structure(self, *, representation=None, runtime=None):
        return self.describe(representation=representation, runtime=runtime)

    def runtime_diagnostics(self, *, representation=None, runtime=None, intent=None):
        from metric.runtime import runtime_diagnostics

        return runtime_diagnostics(
            runtime,
            representation=self._representation_name(representation),
            intent=intent,
        )

    def _compare_records(self, other, align):
        if align == "position":
            return self.records, other.records
        if align != "ids":
            raise ValueError("align must be 'position' or 'ids'")
        if set(self.ids) != set(other.ids):
            raise IncompatibleSpaceError("align='ids' requires both spaces to have the same ids")
        return self.records, [other.record(record_id) for record_id in self.ids]

    def compare(
        self,
        other,
        strategy=None,
        *,
        align="position",
        representation=None,
        other_representation=None,
        runtime=None,
    ):
        require_exact_runtime(runtime)
        from metric.operators import compare_spaces

        left_records, right_records = self._compare_records(other, align)
        return compare_spaces(
            left_records,
            self.metric,
            right_records,
            other.metric,
            strategy,
            left_representation=self._representation_name(representation),
            right_representation=self._representation_name(other_representation),
        )

    def correlate(
        self,
        other,
        strategy=None,
        *,
        align="position",
        representation=None,
        other_representation=None,
        runtime=None,
    ):
        return self.compare(
            other,
            strategy=strategy,
            align=align,
            representation=representation,
            other_representation=other_representation,
            runtime=runtime,
        )


MatrixSpace = FiniteMetricSpace

__all__ = ["FiniteMetricSpace", "MatrixSpace", "Space"]
