"""Finite metric-space helpers for the revived Python API."""

from collections.abc import Mapping
import copy as _copy
import math
import numbers

from metric.exceptions import (
    AmbiguousIntentError,
    MetricContractError,
    MetricInputError,
    MissingMetricError,
    OptionalDependencyError,
    StaleRepresentationError,
    StrategyUnavailableError,
)
from metric.runtime import CachePolicy, require_exact_runtime


_VALIDATION_MODES = {"none", "sample", "strict"}
_MATERIALIZED_CACHE_MODES = {"auto", "materialized"}


class RecordId(int):
    """Default stable record identifier generated by Space."""

    def __new__(cls, value):
        return int.__new__(cls, value)


def _native_euclidean_metric():
    try:
        from metric.distance import Euclidean
    except (ImportError, AttributeError):
        Euclidean = None
    if Euclidean is None:
        raise MissingMetricError(
            "Space.vectors requires metric=... unless the native Euclidean binding is available. "
            "The Python package does not implement Euclidean distance itself."
        )
    return Euclidean()


def _is_native_euclidean_vector_metric(metric):
    try:
        from metric.distance import Euclidean
    except (ImportError, AttributeError):
        return False
    if Euclidean is None:
        return False
    try:
        return isinstance(metric, Euclidean)
    except TypeError:
        return False


def _normalize_validation(validate):
    if not isinstance(validate, str):
        raise TypeError("validate must be a string")
    if validate not in _VALIDATION_MODES:
        raise ValueError(f"validate must be one of {sorted(_VALIDATION_MODES)!r}")
    return validate


def _normalize_cache(cache):
    return cache if isinstance(cache, CachePolicy) else CachePolicy(cache)


def _normalize_record_value_type(value_type):
    aliases = {
        "float": "double",
        "float64": "double",
        "double": "double",
        float: "double",
        "str": "string",
        "string": "string",
        str: "string",
    }
    try:
        return aliases[value_type]
    except KeyError as exc:
        raise ValueError("value_type must be one of 'float', 'double', 'str', or 'string'") from exc


def _native_record_reader(kind, value_type):
    try:
        from metric._impl import metric as native_metric
    except ModuleNotFoundError as exc:
        raise StrategyUnavailableError(
            "native C++ record file I/O is unavailable because metric._impl.metric could not be imported"
        ) from exc

    name = f"read_{kind}_{value_type}_records"
    try:
        return getattr(native_metric, name)
    except AttributeError as exc:
        raise StrategyUnavailableError(f"native C++ record file I/O binding {name} is unavailable") from exc


def _native_record_writer(kind, value_type):
    try:
        from metric._impl import metric as native_metric
    except ModuleNotFoundError as exc:
        raise StrategyUnavailableError(
            "native C++ record file I/O is unavailable because metric._impl.metric could not be imported"
        ) from exc

    name = f"write_{kind}_{value_type}_records"
    try:
        return getattr(native_metric, name)
    except AttributeError as exc:
        raise StrategyUnavailableError(f"native C++ record file I/O binding {name} is unavailable") from exc


def _read_native_delimited_records(
    kind,
    path,
    *,
    value_type,
    has_header,
    trim_fields,
    allow_empty_lines,
    require_uniform_dimension,
    require_finite,
    quote,
):
    normalized = _normalize_record_value_type(value_type)
    reader = _native_record_reader(kind, normalized)
    return reader(
        str(path),
        has_header=has_header,
        trim_fields=trim_fields,
        allow_empty_lines=allow_empty_lines,
        require_uniform_dimension=require_uniform_dimension,
        require_finite=require_finite,
        quote=quote,
    )


def _rows_for_native_export(records, ids, *, value_type, as_scalar, include_ids):
    normalized = _normalize_record_value_type(value_type)
    rows = []
    for row_index, record in enumerate(records):
        if as_scalar or isinstance(record, (str, bytes)):
            row = [record]
        else:
            try:
                row = list(record)
            except TypeError:
                row = [record]
        if not row:
            raise ValueError(f"record {row_index} has no fields")
        if include_ids:
            row = [ids[row_index]] + row
        if normalized == "string":
            row = [str(value) for value in row]
        rows.append(row)
    return rows


def _write_native_delimited_records(
    kind,
    path,
    records,
    ids,
    *,
    value_type,
    as_scalar,
    include_ids,
    header,
    id_header,
    newline_at_end,
    quote,
):
    normalized = _normalize_record_value_type(value_type)
    writer = _native_record_writer(kind, normalized)
    output_header = [] if header is None else list(header)
    if include_ids and output_header:
        output_header = [id_header] + output_header
    writer(
        str(path),
        _rows_for_native_export(
            records,
            ids,
            value_type=normalized,
            as_scalar=as_scalar,
            include_ids=include_ids,
        ),
        newline_at_end=newline_at_end,
        header=output_header,
        quote=quote,
    )
    return path


def _split_record_id_column(records, ids, id_column):
    if id_column is None:
        return records, ids
    if ids is not None:
        raise ValueError("use either ids or id_column, not both")
    if not isinstance(id_column, int):
        raise TypeError("id_column must be an integer column index")

    extracted_ids = []
    feature_records = []
    for row_index, row in enumerate(records):
        if not 0 <= id_column < len(row):
            raise IndexError(f"id_column {id_column} is out of range for row {row_index}")
        extracted_ids.append(row[id_column])
        feature_record = [value for column, value in enumerate(row) if column != id_column]
        if not feature_record:
            raise ValueError("id_column leaves no record fields")
        feature_records.append(feature_record)
    return feature_records, extracted_ids


def _as_scalar_records(records):
    scalar_records = []
    for row_index, row in enumerate(records):
        if len(row) != 1:
            raise ValueError(f"as_scalar=True requires exactly one field per row; row {row_index} has {len(row)}")
        scalar_records.append(row[0])
    return scalar_records


def _load_numpy_array(path, *, allow_pickle):
    try:
        import numpy as np
    except ModuleNotFoundError as exc:
        raise OptionalDependencyError(
            "Space.from_numpy_file requires numpy. Install numpy or use Space.from_csv/Space.from_tsv."
        ) from exc
    return np.load(path, allow_pickle=allow_pickle)


def _validate_distance_value(value, lhs_index, rhs_index):
    if isinstance(value, bool) or not isinstance(value, numbers.Real):
        raise MetricContractError(
            f"metric distance for records {lhs_index} and {rhs_index} must be a real number"
        )
    if not math.isfinite(value):
        raise MetricContractError(
            f"metric distance for records {lhs_index} and {rhs_index} must be finite"
        )
    if value < 0:
        raise MetricContractError(
            f"metric distance for records {lhs_index} and {rhs_index} must be non-negative"
        )
    return value


def _require_native_binding(operation, kind):
    """Raise the adapter-boundary error for an operation with no native binding.

    METRIC is a native C++ finite-metric-space framework. The Python package
    adapts data, marshals results, and exposes bindings; it does not implement
    production algorithms. Search/clustering/embedding/correlation/structure
    operations must run in native C++.
    """
    raise StrategyUnavailableError(
        f"{operation} requires native C++ binding support. The METRIC Python package is an "
        f"adapter-only surface: {kind} must run in native C++ and be reached through a binding, "
        f"and is not implemented in Python. No native binding for this operation is exposed in "
        f"metric._impl yet."
    )


class FiniteMetricSpace:
    """Explicit finite metric space backed by a pairwise distance matrix."""

    def __init__(
        self,
        records,
        metric=None,
        source_space=None,
        representation="metric_space",
        ids=None,
        name=None,
        metadata=None,
        validate="sample",
        copy=False,
        cache="auto",
    ):
        if metric is None:
            raise MissingMetricError(
                "Space requires an explicit metric for arbitrary records. "
                "Use Space(records, metric=Edit()) or another callable metric."
            )
        validate = _normalize_validation(validate)
        cache = _normalize_cache(cache)
        if not isinstance(copy, bool):
            raise TypeError("copy must be a bool")
        self.records = [_copy.copy(record) for record in records] if copy else list(records)
        self.ids = [RecordId(index) for index in range(len(self.records))] if ids is None else list(ids)
        if len(self.ids) != len(self.records):
            raise ValueError("ids must have the same length as records")
        if len(set(self.ids)) != len(self.ids):
            raise ValueError("ids must be unique")
        self._id_to_index = {record_id: index for index, record_id in enumerate(self.ids)}
        self.metric = metric
        self.name = name
        self.metadata = {} if metadata is None else dict(metadata)
        self.source_space = source_space
        self.source_version = source_space.version() if source_space is not None else None
        self.representation = representation
        self.validate = validate
        self.cache = cache
        self._version = 0
        self._lazy_distances = {}
        self._distances = None
        if cache.mode in _MATERIALIZED_CACHE_MODES:
            self._distances = [
                [self._compute_distance(lhs_index, rhs_index) for rhs_index in range(len(self.records))]
                for lhs_index in range(len(self.records))
            ]
        elif validate == "strict":
            self._validate_all_distances()
        else:
            self._validate_sample_distances()

    def __len__(self):
        return len(self.records)

    def __repr__(self):
        record_type = type(self.records[0]).__name__ if self.records else "empty"
        return (
            f"{type(self).__name__}(size={len(self)}, "
            f"metric={self.metric!r}, records={record_type}, name={self.name!r})"
        )

    def __getitem__(self, index):
        return self.records[index]

    def __call__(self, lhs_index, rhs_index):
        return self.distance(lhs_index, rhs_index)

    @classmethod
    def vectors(cls, records, metric=None, **kwargs):
        """Construct a finite metric space from vector records.

        Defaults to the native Euclidean binding when it is available. The
        Python package does not implement vector-distance math itself.
        """

        return cls(
            records,
            metric=_native_euclidean_metric() if metric is None else metric,
            **kwargs,
        )

    @classmethod
    def from_dataframe(cls, dataframe, metric=None, id_column=None, **kwargs):
        if metric is None:
            raise MissingMetricError(
                "Space.from_dataframe requires an explicit metric. "
                "Use Space.from_dataframe(df, metric=callable)."
            )
        if id_column is not None and "ids" in kwargs:
            raise ValueError("use either id_column or ids, not both")
        if not hasattr(dataframe, "to_dict"):
            raise TypeError("dataframe must provide to_dict('records')")

        try:
            rows = dataframe.to_dict("records")
        except TypeError:
            rows = dataframe.to_dict(orient="records")

        ids = None
        records = list(rows)
        if id_column is not None:
            ids = []
            feature_records = []
            for row in records:
                if not isinstance(row, Mapping):
                    raise TypeError("dataframe records must be mappings when id_column is used")
                if id_column not in row:
                    raise KeyError(f"id_column {id_column!r} is not present in every row")
                ids.append(row[id_column])
                feature_records.append({
                    column: value
                    for column, value in row.items()
                    if column != id_column
                })
            records = feature_records

        return cls(records, metric=metric, ids=ids, **kwargs)

    @classmethod
    def from_csv(
        cls,
        path,
        metric=None,
        *,
        value_type="float",
        has_header=False,
        id_column=None,
        ids=None,
        as_scalar=False,
        trim_fields=True,
        allow_empty_lines=True,
        require_uniform_dimension=True,
        require_finite=True,
        quote='"',
        **kwargs,
    ):
        """Construct a finite metric space from native C++ CSV record import."""

        records = _read_native_delimited_records(
            "csv",
            path,
            value_type=value_type,
            has_header=has_header,
            trim_fields=trim_fields,
            allow_empty_lines=allow_empty_lines,
            require_uniform_dimension=require_uniform_dimension,
            require_finite=require_finite,
            quote=quote,
        )
        records, ids = _split_record_id_column(records, ids, id_column)
        if as_scalar:
            records = _as_scalar_records(records)

        if metric is None:
            if _normalize_record_value_type(value_type) == "double" and not as_scalar:
                return cls.vectors(records, ids=ids, **kwargs)
            raise MissingMetricError(
                "Space.from_csv requires metric=... for non-vector or string records. "
                "Numeric vector CSV rows use the native Euclidean metric by default."
            )
        return cls(records, metric=metric, ids=ids, **kwargs)

    @classmethod
    def from_tsv(
        cls,
        path,
        metric=None,
        *,
        value_type="float",
        has_header=False,
        id_column=None,
        ids=None,
        as_scalar=False,
        trim_fields=True,
        allow_empty_lines=True,
        require_uniform_dimension=True,
        require_finite=True,
        quote='"',
        **kwargs,
    ):
        """Construct a finite metric space from native C++ TSV record import."""

        records = _read_native_delimited_records(
            "tsv",
            path,
            value_type=value_type,
            has_header=has_header,
            trim_fields=trim_fields,
            allow_empty_lines=allow_empty_lines,
            require_uniform_dimension=require_uniform_dimension,
            require_finite=require_finite,
            quote=quote,
        )
        records, ids = _split_record_id_column(records, ids, id_column)
        if as_scalar:
            records = _as_scalar_records(records)

        if metric is None:
            if _normalize_record_value_type(value_type) == "double" and not as_scalar:
                return cls.vectors(records, ids=ids, **kwargs)
            raise MissingMetricError(
                "Space.from_tsv requires metric=... for non-vector or string records. "
                "Numeric vector TSV rows use the native Euclidean metric by default."
            )
        return cls(records, metric=metric, ids=ids, **kwargs)

    @classmethod
    def from_numpy_file(
        cls,
        path,
        metric=None,
        *,
        ids=None,
        allow_pickle=False,
        **kwargs,
    ):
        """Construct a finite metric space from a NumPy ``.npy`` array."""

        array = _load_numpy_array(path, allow_pickle=allow_pickle)
        if array.ndim != 2:
            raise ValueError("Space.from_numpy_file requires a 2D array shaped as records x fields")
        records = array.tolist()
        if metric is None:
            return cls.vectors(records, ids=ids, **kwargs)
        return cls(records, metric=metric, ids=ids, **kwargs)

    def version(self):
        return self._version

    def touch(self):
        self._version += 1
        return self._version

    def is_stale(self):
        return self.source_space is not None and self.source_space.version() != self.source_version

    def ensure_fresh(self):
        if self.is_stale():
            raise StaleRepresentationError(
                f"{self.representation} representation is stale: source version {self.source_space.version()} "
                f"does not match representation version {self.source_version}. "
                "Rebuild the representation from the source space."
            )
        return self

    def distance(self, lhs_index, rhs_index):
        self.ensure_fresh()
        if self._distances is not None:
            return self._distances[lhs_index][rhs_index]
        if self.cache.mode == "lazy":
            key = (lhs_index, rhs_index)
            if key not in self._lazy_distances:
                self._lazy_distances[key] = self._compute_distance(lhs_index, rhs_index)
            return self._lazy_distances[key]
        return self._compute_distance(lhs_index, rhs_index)

    def record(self, record_id):
        return self.records[self._id_to_index[record_id]]

    def pairwise_distances(self):
        self.ensure_fresh()
        if self._distances is not None:
            return [row[:] for row in self._distances]
        return [
            [self.distance(lhs_index, rhs_index) for rhs_index in range(len(self.records))]
            for lhs_index in range(len(self.records))
        ]

    def pairwise(self, ids=None):
        self.ensure_fresh()
        if ids is None:
            return self.pairwise_distances()

        positions = [self._id_to_index[record_id] for record_id in ids]
        return [
            [self.distance(lhs, rhs) for rhs in positions]
            for lhs in positions
        ]

    def to_csv(
        self,
        path,
        *,
        value_type="float",
        as_scalar=False,
        include_ids=False,
        header=None,
        id_header="id",
        newline_at_end=True,
        quote='"',
    ):
        """Export records through the native C++ CSV writer."""

        self.ensure_fresh()
        return _write_native_delimited_records(
            "csv",
            path,
            self.records,
            self.ids,
            value_type=value_type,
            as_scalar=as_scalar,
            include_ids=include_ids,
            header=header,
            id_header=id_header,
            newline_at_end=newline_at_end,
            quote=quote,
        )

    def to_tsv(
        self,
        path,
        *,
        value_type="float",
        as_scalar=False,
        include_ids=False,
        header=None,
        id_header="id",
        newline_at_end=True,
        quote='"',
    ):
        """Export records through the native C++ TSV writer."""

        self.ensure_fresh()
        return _write_native_delimited_records(
            "tsv",
            path,
            self.records,
            self.ids,
            value_type=value_type,
            as_scalar=as_scalar,
            include_ids=include_ids,
            header=header,
            id_header=id_header,
            newline_at_end=newline_at_end,
            quote=quote,
        )

    def to_matrix(self):
        return FiniteMetricSpace(
            self.records,
            self.metric,
            source_space=self,
            representation="matrix",
            ids=self.ids,
            name=self.name,
            metadata=self.metadata,
            validate=self.validate,
            cache="materialized",
        )

    def to_tree(self):
        from metric.representations import TreeIndex

        return TreeIndex(self)

    def to_graph(self, count):
        from metric.representations import GraphIndex

        return GraphIndex(self, count)

    def _with_space_record_ids(self, result):
        from metric.operators import Neighbor, NeighborResult

        def map_neighbor(neighbor):
            return Neighbor(
                id=self.ids[int(neighbor.id)],
                record=neighbor.record,
                distance=neighbor.distance,
                rank=neighbor.rank,
            )

        mapped_neighbors = tuple(map_neighbor(neighbor) for neighbor in result.neighbors)
        mapped_rows = tuple(tuple(map_neighbor(neighbor) for neighbor in row) for row in result.rows)
        return NeighborResult(
            query=result.query,
            query_id=result.query_id,
            neighbors=mapped_neighbors,
            rows=mapped_rows,
            distances=result.distances,
            exact=result.exact,
            strategy=result.strategy,
            representation=result.representation,
            diagnostics=result.diagnostics,
        )

    def knn(self, query, k=1):
        """Exact-scan k-nearest neighbors through the native C++ binding."""
        from metric.operators import nearest_neighbors

        return self._with_space_record_ids(nearest_neighbors(self.records, self.metric, query, count=k))

    def nn(self, query):
        """Exact-scan nearest neighbor through the native C++ binding."""
        result = self.knn(query, k=1)
        return result.neighbors[0] if result.neighbors else None

    def rnn(self, query, radius):
        """Exact-scan radius neighbors through the native C++ binding."""
        from metric.operators import range_neighbors

        return self._with_space_record_ids(range_neighbors(self.records, self.metric, query, radius))

    def neighbors(self, query, k=None, count=None, radius=None):
        """Exact-scan neighbor query through the native C++ binding."""
        if radius is not None:
            return self.rnn(query, radius)
        from metric.operators import nearest_neighbors

        return self._with_space_record_ids(nearest_neighbors(self.records, self.metric, query, k=k, count=count))

    def _compute_distance(self, lhs_index, rhs_index):
        value = self.metric(self.records[lhs_index], self.records[rhs_index])
        if self.validate != "none":
            _validate_distance_value(value, lhs_index, rhs_index)
        return value

    def _validate_sample_distances(self):
        if self.validate == "none" or not self.records:
            return
        sample_size = min(len(self.records), 3)
        for lhs_index in range(sample_size):
            for rhs_index in range(sample_size):
                self._compute_distance(lhs_index, rhs_index)

    def _validate_all_distances(self):
        for lhs_index in range(len(self.records)):
            for rhs_index in range(len(self.records)):
                self._compute_distance(lhs_index, rhs_index)


class Space(FiniteMetricSpace):
    """Intent-first facade for a finite metric space.

    The revived Python engine facade starts from operations backed by stable
    strategy and result contracts. Learned embedding paths stay out of the core
    facade until they have deterministic coverage.
    """

    def neighbors(
        self,
        query=None,
        k=None,
        count=None,
        radius=None,
        *,
        include_self=False,
        strategy=None,
        representation=None,
        runtime=None,
    ):
        """Exact-scan neighbor query through the native C++ binding."""
        require_exact_runtime(runtime)
        if strategy is not None:
            raise StrategyUnavailableError(
                "Space.neighbors strategy selection is not promoted in Python yet; omit strategy for native exact scan"
            )
        if representation is not None:
            representation.ensure_fresh()
        if radius is not None:
            return self.within_radius(query, radius)
        return super().neighbors(query, k=k, count=count)

    def nearest(self, query):
        """Exact-scan nearest neighbor through the native C++ binding."""
        return self.nn(query)

    def within_radius(self, query, radius):
        """Exact-scan radius neighbors through the native C++ binding."""
        return self.rnn(query, radius)

    def groups(self, strategy=None, *, count="auto", radius=None, min_size=1, representation=None, runtime=None):
        """Group records via clustering (native-only)."""
        _require_native_binding("Space.groups(...)", "clustering")

    def outliers(
        self,
        strategy=None,
        *,
        count=None,
        fraction=0.05,
        threshold=None,
        representation=None,
        runtime=None,
    ):
        """Find unusual records (native-only)."""
        _require_native_binding("Space.outliers(...)", "outlier detection")

    def denoise(
        self,
        strategy=None,
        *,
        count=None,
        fraction=0.05,
        threshold=None,
        strength="auto",
        representation=None,
        runtime=None,
    ):
        """Filter noise records into a derived metric space (native-only)."""
        _require_native_binding("Space.denoise(...)", "density denoising")

    def representatives(self, k=None, strategy=None, *, count=None, representation=None, runtime=None):
        """Select representative records through the native C++ binding."""
        require_exact_runtime(runtime)
        from metric.operators import RepresentativeSet, find_representatives

        result = find_representatives(
            self.records,
            self.metric,
            k=k,
            count=count,
            strategy=strategy,
            representation=self._representation_name(representation),
        )
        return RepresentativeSet(
            representatives=tuple(self.ids[int(index)] for index in result.representatives),
            nearest_representative_distances=result.nearest_representative_distances,
            record_count=result.record_count,
            requested_count=result.requested_count,
            coverage_radius=result.coverage_radius,
            average_nearest_distance=result.average_nearest_distance,
            exact=result.exact,
            strategy=result.strategy,
            representation=result.representation,
        )

    def _representation_name(self, representation):
        representation_name = "metric_space"
        if representation is not None:
            representation.ensure_fresh()
            representation_name = getattr(representation, "representation", representation_name)
        return representation_name

    def reduce(self, count=None, strategy=None, *, representation=None, runtime=None):
        """Reduce the space to representative records through the native C++ binding."""
        require_exact_runtime(runtime)
        from metric.operators import ReductionResult, reduce_space

        result = reduce_space(
            self.records,
            self.metric,
            count=count,
            strategy=strategy,
            representation=self._representation_name(representation),
        )
        selected_positions = [int(index) for index in result.source_record_ids]
        return ReductionResult(
            space=Space(
                [self.records[index] for index in selected_positions],
                self.metric,
                ids=[self.ids[index] for index in selected_positions],
                name=self.name,
                metadata=self.metadata,
                validate=self.validate,
                cache=self.cache,
            ),
            source_record_ids=tuple(self.ids[index] for index in selected_positions),
            assignments=result.assignments,
            nearest_representative_distances=result.nearest_representative_distances,
            source_record_count=result.source_record_count,
            reduced_record_count=result.reduced_record_count,
            exact=result.exact,
            operator_name=result.operator_name,
            strategy=result.strategy,
            representation=result.representation,
            inverse_supported=result.inverse_supported,
        )

    def compress(self, count=None, strategy=None, *, representation=None, runtime=None):
        """Compress the space by retaining representatives through the native C++ binding."""
        require_exact_runtime(runtime)
        from metric.operators import CompressionResult

        reduced = self.reduce(count=count, strategy=strategy, representation=representation, runtime=runtime)
        ratio = (reduced.reduced_record_count / reduced.source_record_count) if reduced.source_record_count else 0.0
        return CompressionResult(
            space=reduced.space,
            source_record_ids=reduced.source_record_ids,
            assignments=reduced.assignments,
            nearest_representative_distances=reduced.nearest_representative_distances,
            source_record_count=reduced.source_record_count,
            compressed_record_count=reduced.reduced_record_count,
            compression_ratio=ratio,
            exact=reduced.exact,
            operator_name="compress",
            compression="representatives",
            strategy=reduced.strategy,
            representation=reduced.representation,
            lossy=reduced.reduced_record_count < reduced.source_record_count,
            inverse_supported=False,
        )

    def map(self, transform=None, metric=None, *, target=None, strategy=None, representation=None, runtime=None):
        require_exact_runtime(runtime)
        from metric.strategies import PhateAE

        if isinstance(strategy, PhateAE):
            if transform is not None or target is not None or metric is not None:
                raise AmbiguousIntentError(
                    "PhateAE native mappings derive their target from the source space; "
                    "omit transform and target, and do not pass a metric"
                )
            if not _is_native_euclidean_vector_metric(self.metric):
                raise StrategyUnavailableError(
                    "Space.map(strategy=PhateAE(...)) only delegates to the native C++ binding for "
                    "Space.vectors(...) values that use the default native-compatible Euclidean vector metric. "
                    "Custom Python metrics are not ignored; use "
                    "metric.mappings.native_phate_autoencoder_fit_vectors(...) explicitly for native Euclidean "
                    "vector rows or stay in C++ for custom metric semantics."
                )

            from metric.mappings import native_phate_autoencoder_fit_vectors
            from metric.operators import MappingResult

            self.ensure_fresh()
            representation_name = self._representation_name(representation)
            model = native_phate_autoencoder_fit_vectors(
                self.records,
                dimensions=strategy.dimensions,
                epochs=strategy.epochs,
                learning_rate=strategy.learning_rate,
                diffusion_steps=strategy.diffusion_steps,
                kernel_scale=1.0 if strategy.kernel_scale is None else strategy.kernel_scale,
                reconstruction_weight=strategy.reconstruction_weight,
                geometry_weight=strategy.geometry_weight,
                seed=strategy.seed,
                distance_provider=strategy.distance_provider,
                affinity_kernel=strategy.affinity_kernel,
                diffusion_operator=strategy.diffusion_operator,
            )
            latent_records = model.transform(self.records)
            latent_space = Space.vectors(
                latent_records,
                ids=self.ids,
                validate="none",
                cache="none",
                metadata={
                    "source_space_version": self.version(),
                    "mapping": model.mapping,
                    "strategy": model.strategy,
                    "distance_provider": model.distance_provider,
                    "affinity_kernel": model.affinity_kernel,
                    "diffusion_operator": model.diffusion_operator,
                },
            )
            source_ids = tuple(self.ids)
            return MappingResult(
                space=latent_space,
                source_record_ids=source_ids,
                source_record_count=len(self.records),
                target_record_count=len(latent_records),
                exact=True,
                operator_name="map",
                mapping=model.mapping,
                strategy=model.strategy,
                representation=representation_name,
                inverse_supported=model.inverse_supported,
                source_records=tuple((record_id,) for record_id in source_ids),
                representative_records=source_ids,
                fitted_model=model,
            )

        if transform is None and target is None:
            raise AmbiguousIntentError("Space.map requires transform=... or target=...")
        if transform is not None and target is not None:
            raise AmbiguousIntentError("Space.map uses either transform or target, not both")
        if strategy is not None:
            raise StrategyUnavailableError(
                "Space.map strategy mappings are not promoted yet. "
                "Use transform=... with metric=... for deterministic maps."
            )
        if target is not None:
            raise StrategyUnavailableError(
                "Space.map target mappings are not promoted yet. "
                "Use transform=... with metric=... for deterministic maps."
            )

        from metric.operators import map_space

        return map_space(
            self.records,
            transform,
            self.metric if metric is None else metric,
            representation=self._representation_name(representation),
        )

    def embed(self, dimensions=2, strategy=None, *, representation=None, runtime=None):
        """Embed the space into Euclidean coordinates (native-only)."""
        _require_native_binding("Space.embed(...)", "metric-space embedding (e.g. classical MDS)")

    def describe(self, *, representation=None, runtime=None):
        """Describe exact finite-space structure through the native C++ binding."""
        require_exact_runtime(runtime)
        from metric.operators import describe_structure

        return describe_structure(
            self.records,
            self.metric,
            representation=self._representation_name(representation),
        )

    def describe_structure(self, *, representation=None, runtime=None):
        """Describe exact finite-space structure through the native C++ binding."""
        return self.describe(representation=representation, runtime=runtime)

    def runtime_diagnostics(self, *, representation=None, runtime=None, intent=None):
        """Inspect the normalized runtime policy and chosen representation.

        Adapter: this reports policy metadata only; it runs no algorithm.
        """
        from metric.runtime import runtime_diagnostics

        return runtime_diagnostics(
            runtime,
            representation=self._representation_name(representation),
            intent=intent,
        )

    def compare(
        self,
        other,
        strategy=None,
        *,
        align="position",
        other_metric=None,
        representation=None,
        other_representation=None,
        runtime=None,
    ):
        """Compare aligned finite metric spaces (native-only)."""
        _require_native_binding("Space.compare(...)", "cross-space distance-profile correlation")

    def correlate(
        self,
        other,
        strategy=None,
        *,
        align="position",
        other_metric=None,
        representation=None,
        other_representation=None,
        runtime=None,
    ):
        """Correlate aligned finite metric spaces (native-only)."""
        _require_native_binding("Space.correlate(...)", "cross-space distance-profile correlation")


MatrixSpace = FiniteMetricSpace

__all__ = ["FiniteMetricSpace", "MatrixSpace", "Space"]
