"""Finite metric-space helpers for the revived Python API."""

from collections.abc import Mapping
import copy as _copy
import math
import numbers

from metric.exceptions import (
    AmbiguousIntentError,
    MetricContractError,
    MetricInputError,
    MissingMetricError,
    StaleRepresentationError,
    StrategyUnavailableError,
)
from metric.runtime import CachePolicy, require_exact_runtime


_VALIDATION_MODES = {"none", "sample", "strict"}
_MATERIALIZED_CACHE_MODES = {"auto", "materialized"}


class RecordId(int):
    """Default stable record identifier generated by Space."""

    def __new__(cls, value):
        return int.__new__(cls, value)


def _native_euclidean_metric():
    try:
        from metric.distance import Euclidean
    except (ImportError, AttributeError):
        Euclidean = None
    if Euclidean is None:
        raise MissingMetricError(
            "Space.vectors requires metric=... unless the native Euclidean binding is available. "
            "The Python package does not implement Euclidean distance itself."
        )
    return Euclidean()


def _is_native_euclidean_vector_metric(metric):
    try:
        from metric.distance import Euclidean
    except (ImportError, AttributeError):
        return False
    if Euclidean is None:
        return False
    try:
        return isinstance(metric, Euclidean)
    except TypeError:
        return False


def _normalize_validation(validate):
    if not isinstance(validate, str):
        raise TypeError("validate must be a string")
    if validate not in _VALIDATION_MODES:
        raise ValueError(f"validate must be one of {sorted(_VALIDATION_MODES)!r}")
    return validate


def _normalize_cache(cache):
    return cache if isinstance(cache, CachePolicy) else CachePolicy(cache)


def _validate_distance_value(value, lhs_index, rhs_index):
    if isinstance(value, bool) or not isinstance(value, numbers.Real):
        raise MetricContractError(
            f"metric distance for records {lhs_index} and {rhs_index} must be a real number"
        )
    if not math.isfinite(value):
        raise MetricContractError(
            f"metric distance for records {lhs_index} and {rhs_index} must be finite"
        )
    if value < 0:
        raise MetricContractError(
            f"metric distance for records {lhs_index} and {rhs_index} must be non-negative"
        )
    return value


def _require_native_binding(operation, kind):
    """Raise the adapter-boundary error for an operation with no native binding.

    METRIC is a native C++ finite-metric-space framework. The Python package
    adapts data, marshals results, and exposes bindings; it does not implement
    production algorithms. Search/clustering/embedding/correlation/structure
    operations must run in native C++.
    """
    raise StrategyUnavailableError(
        f"{operation} requires native C++ binding support. The METRIC Python package is an "
        f"adapter-only surface: {kind} must run in native C++ and be reached through a binding, "
        f"and is not implemented in Python. No native binding for this operation is exposed in "
        f"metric._impl yet."
    )


class FiniteMetricSpace:
    """Explicit finite metric space backed by a pairwise distance matrix."""

    def __init__(
        self,
        records,
        metric=None,
        source_space=None,
        representation="metric_space",
        ids=None,
        name=None,
        metadata=None,
        validate="sample",
        copy=False,
        cache="auto",
    ):
        if metric is None:
            raise MissingMetricError(
                "Space requires an explicit metric for arbitrary records. "
                "Use Space(records, metric=Edit()) or another callable metric."
            )
        validate = _normalize_validation(validate)
        cache = _normalize_cache(cache)
        if not isinstance(copy, bool):
            raise TypeError("copy must be a bool")
        self.records = [_copy.copy(record) for record in records] if copy else list(records)
        self.ids = [RecordId(index) for index in range(len(self.records))] if ids is None else list(ids)
        if len(self.ids) != len(self.records):
            raise ValueError("ids must have the same length as records")
        if len(set(self.ids)) != len(self.ids):
            raise ValueError("ids must be unique")
        self._id_to_index = {record_id: index for index, record_id in enumerate(self.ids)}
        self.metric = metric
        self.name = name
        self.metadata = {} if metadata is None else dict(metadata)
        self.source_space = source_space
        self.source_version = source_space.version() if source_space is not None else None
        self.representation = representation
        self.validate = validate
        self.cache = cache
        self._version = 0
        self._lazy_distances = {}
        self._distances = None
        if cache.mode in _MATERIALIZED_CACHE_MODES:
            self._distances = [
                [self._compute_distance(lhs_index, rhs_index) for rhs_index in range(len(self.records))]
                for lhs_index in range(len(self.records))
            ]
        elif validate == "strict":
            self._validate_all_distances()
        else:
            self._validate_sample_distances()

    def __len__(self):
        return len(self.records)

    def __repr__(self):
        record_type = type(self.records[0]).__name__ if self.records else "empty"
        return (
            f"{type(self).__name__}(size={len(self)}, "
            f"metric={self.metric!r}, records={record_type}, name={self.name!r})"
        )

    def __getitem__(self, index):
        return self.records[index]

    def __call__(self, lhs_index, rhs_index):
        return self.distance(lhs_index, rhs_index)

    @classmethod
    def vectors(cls, records, metric=None, **kwargs):
        """Construct a finite metric space from vector records.

        Defaults to the native Euclidean binding when it is available. The
        Python package does not implement vector-distance math itself.
        """

        return cls(
            records,
            metric=_native_euclidean_metric() if metric is None else metric,
            **kwargs,
        )

    @classmethod
    def from_dataframe(cls, dataframe, metric=None, id_column=None, **kwargs):
        if metric is None:
            raise MissingMetricError(
                "Space.from_dataframe requires an explicit metric. "
                "Use Space.from_dataframe(df, metric=callable)."
            )
        if id_column is not None and "ids" in kwargs:
            raise ValueError("use either id_column or ids, not both")
        if not hasattr(dataframe, "to_dict"):
            raise TypeError("dataframe must provide to_dict('records')")

        try:
            rows = dataframe.to_dict("records")
        except TypeError:
            rows = dataframe.to_dict(orient="records")

        ids = None
        records = list(rows)
        if id_column is not None:
            ids = []
            feature_records = []
            for row in records:
                if not isinstance(row, Mapping):
                    raise TypeError("dataframe records must be mappings when id_column is used")
                if id_column not in row:
                    raise KeyError(f"id_column {id_column!r} is not present in every row")
                ids.append(row[id_column])
                feature_records.append({
                    column: value
                    for column, value in row.items()
                    if column != id_column
                })
            records = feature_records

        return cls(records, metric=metric, ids=ids, **kwargs)

    @classmethod
    def from_csv(cls, path, metric=None, *, has_header=True, id_column=None, delimiter=",", **kwargs):
        """Load numeric vector records from a CSV file.

        Convenience I/O glue: each non-id column becomes a float feature, and the
        space defaults to the native Euclidean metric like ``Space.vectors`` when
        ``metric`` is not given. This is data marshalling, not a distance
        algorithm; for non-numeric or structured rows use ``from_dataframe``.
        Raises ``MetricInputError`` with the offending row/column on a non-numeric
        cell or an empty file.
        """

        import csv as _csv

        with open(path, newline="") as handle:
            rows = list(_csv.reader(handle, delimiter=delimiter))
        if not rows:
            raise MetricInputError(f"Space.from_csv: {path!r} contains no rows")

        header = None
        if has_header:
            header = rows[0]
            rows = rows[1:]

        id_index = None
        if id_column is not None:
            if header is None:
                raise ValueError("Space.from_csv: id_column requires has_header=True")
            if id_column not in header:
                raise KeyError(f"Space.from_csv: id_column {id_column!r} is not in the header")
            id_index = header.index(id_column)

        ids = [] if id_index is not None else None
        records = []
        for row_number, row in enumerate(rows):
            values = []
            for column_index, cell in enumerate(row):
                if column_index == id_index:
                    ids.append(cell)
                    continue
                try:
                    values.append(float(cell))
                except (TypeError, ValueError) as error:
                    raise MetricInputError(
                        f"Space.from_csv: non-numeric value {cell!r} at row {row_number}, column {column_index}"
                    ) from error
            records.append(values)

        chosen_metric = _native_euclidean_metric() if metric is None else metric
        return cls(records, metric=chosen_metric, ids=ids, **kwargs)

    def version(self):
        return self._version

    def touch(self):
        self._version += 1
        return self._version

    def is_stale(self):
        return self.source_space is not None and self.source_space.version() != self.source_version

    def ensure_fresh(self):
        if self.is_stale():
            raise StaleRepresentationError(
                f"{self.representation} representation is stale: source version {self.source_space.version()} "
                f"does not match representation version {self.source_version}. "
                "Rebuild the representation from the source space."
            )
        return self

    def distance(self, lhs_index, rhs_index):
        self.ensure_fresh()
        if self._distances is not None:
            return self._distances[lhs_index][rhs_index]
        if self.cache.mode == "lazy":
            key = (lhs_index, rhs_index)
            if key not in self._lazy_distances:
                self._lazy_distances[key] = self._compute_distance(lhs_index, rhs_index)
            return self._lazy_distances[key]
        return self._compute_distance(lhs_index, rhs_index)

    def record(self, record_id):
        return self.records[self._id_to_index[record_id]]

    def pairwise_distances(self):
        self.ensure_fresh()
        if self._distances is not None:
            return [row[:] for row in self._distances]
        return [
            [self.distance(lhs_index, rhs_index) for rhs_index in range(len(self.records))]
            for lhs_index in range(len(self.records))
        ]

    def pairwise(self, ids=None):
        self.ensure_fresh()
        if ids is None:
            return self.pairwise_distances()

        positions = [self._id_to_index[record_id] for record_id in ids]
        return [
            [self.distance(lhs, rhs) for rhs in positions]
            for lhs in positions
        ]

    def to_matrix(self):
        return FiniteMetricSpace(
            self.records,
            self.metric,
            source_space=self,
            representation="matrix",
            ids=self.ids,
            name=self.name,
            metadata=self.metadata,
            validate=self.validate,
            cache="materialized",
        )

    def to_tree(self):
        from metric.representations import TreeIndex

        return TreeIndex(self)

    def to_graph(self, count):
        from metric.representations import GraphIndex

        return GraphIndex(self, count)

    def _native_exact_matrix(self):
        """Build (and cache) a native exact-scan ``Matrix`` for this space.

        The neighbor search itself runs in native C++ (``metric._impl.space``);
        the Python side only marshals the query and the result. Returns ``None``
        when the metric is not a native vector metric that the space extension
        instantiates (e.g. a custom Python callable, or a metric whose record
        type is not yet bound), in which case the caller raises the
        adapter-boundary error. Cached and invalidated on the space version.
        """
        self.ensure_fresh()
        version = self.version()
        if getattr(self, "_native_matrix", None) is not None and getattr(
            self, "_native_matrix_version", None
        ) == version:
            return self._native_matrix
        metric = self.metric
        if not str(getattr(type(metric), "__module__", "")).startswith("metric._impl"):
            return None
        try:
            from metric._impl import space as _native_space
        except ModuleNotFoundError:
            return None
        try:
            matrix = _native_space.create_matrix(metric, list(self.records))
        except (TypeError, RuntimeError, ValueError):
            return None
        self._native_matrix = matrix
        self._native_matrix_version = version
        return matrix

    def _neighbor(self, index, distance, rank):
        from metric.operators import Neighbor

        return Neighbor(
            id=self.ids[index],
            record=self.records[index],
            distance=distance,
            rank=rank,
        )

    def _neighbor_result(self, query, pairs, *, strategy, representation):
        from metric.operators import NeighborResult

        neighbors = tuple(
            self._neighbor(index, distance, rank)
            for rank, (index, distance) in enumerate(pairs)
        )
        return NeighborResult(
            query=query,
            query_id=None,
            neighbors=neighbors,
            rows=(),
            distances=tuple(distance for _, distance in pairs),
            exact=True,
            strategy=strategy,
            representation=representation,
            diagnostics=None,
        )

    def _exact_neighbor_pairs(self, query, *, k=None, count=None, radius=None):
        """Run the native exact neighbor search; return (id, distance) pairs or None."""
        matrix = self._native_exact_matrix()
        if matrix is None:
            return None
        requested = k if k is not None else count
        if radius is not None and requested is None:
            return list(matrix.rnn(query, radius))
        if requested is None:
            requested = 1
        pairs = list(matrix.knn(query, int(requested)))
        if radius is not None:
            pairs = [pair for pair in pairs if pair[1] <= radius]
        return pairs

    def knn(self, query, k=1):
        """Exact-scan k-nearest neighbors via the native binding."""
        pairs = self._exact_neighbor_pairs(query, k=k)
        if pairs is None:
            _require_native_binding("FiniteMetricSpace.knn(...)", "exact-scan neighbor search")
        return self._neighbor_result(query, pairs, strategy="exact_scan", representation=self.representation)

    def nn(self, query):
        """Exact-scan nearest neighbor via the native binding."""
        pairs = self._exact_neighbor_pairs(query, k=1)
        if pairs is None:
            _require_native_binding("FiniteMetricSpace.nn(...)", "exact-scan neighbor search")
        if not pairs:
            return None
        index, distance = pairs[0]
        return self._neighbor(index, distance, 0)

    def rnn(self, query, radius):
        """Exact-scan radius neighbors via the native binding."""
        pairs = self._exact_neighbor_pairs(query, radius=radius)
        if pairs is None:
            _require_native_binding("FiniteMetricSpace.rnn(...)", "exact-scan radius search")
        return self._neighbor_result(query, pairs, strategy="exact_range", representation=self.representation)

    def neighbors(self, query, k=None, count=None, radius=None):
        """Exact-scan neighbor query via the native binding."""
        pairs = self._exact_neighbor_pairs(query, k=k, count=count, radius=radius)
        if pairs is None:
            _require_native_binding("FiniteMetricSpace.neighbors(...)", "exact-scan neighbor search")
        strategy = "exact_range" if (radius is not None and k is None and count is None) else "exact_scan"
        return self._neighbor_result(query, pairs, strategy=strategy, representation=self.representation)

    def _compute_distance(self, lhs_index, rhs_index):
        value = self.metric(self.records[lhs_index], self.records[rhs_index])
        if self.validate != "none":
            _validate_distance_value(value, lhs_index, rhs_index)
        return value

    def _validate_sample_distances(self):
        if self.validate == "none" or not self.records:
            return
        sample_size = min(len(self.records), 3)
        for lhs_index in range(sample_size):
            for rhs_index in range(sample_size):
                self._compute_distance(lhs_index, rhs_index)

    def _validate_all_distances(self):
        for lhs_index in range(len(self.records)):
            for rhs_index in range(len(self.records)):
                self._compute_distance(lhs_index, rhs_index)


class Space(FiniteMetricSpace):
    """Intent-first facade for a finite metric space.

    The revived Python engine facade starts from operations backed by stable
    strategy and result contracts. Learned embedding paths stay out of the core
    facade until they have deterministic coverage.
    """

    def neighbors(
        self,
        query=None,
        k=None,
        count=None,
        radius=None,
        *,
        include_self=False,
        strategy=None,
        representation=None,
        runtime=None,
    ):
        """Exact-scan neighbor query via the native binding.

        Delegates the search to native C++ (``metric._impl.space``) for spaces
        built on a native vector metric. A custom Python metric, an explicit
        strategy object, or the no-query per-record batch mode are not wired
        yet and raise the adapter-boundary error.
        """
        if runtime is not None:
            require_exact_runtime(runtime)
        if strategy is not None or query is None:
            _require_native_binding("Space.neighbors(...)", "exact-scan neighbor search")
        pairs = self._exact_neighbor_pairs(query, k=k, count=count, radius=radius)
        if pairs is None:
            _require_native_binding("Space.neighbors(...)", "exact-scan neighbor search")
        label = "exact_range" if (radius is not None and k is None and count is None) else "exact_scan"
        result_representation = getattr(representation, "representation", self.representation)
        return self._neighbor_result(query, pairs, strategy=label, representation=result_representation)

    def nearest(self, query):
        """Exact-scan nearest neighbor via the native binding."""
        pairs = self._exact_neighbor_pairs(query, k=1)
        if pairs is None:
            _require_native_binding("Space.nearest(...)", "exact-scan neighbor search")
        if not pairs:
            return None
        index, distance = pairs[0]
        return self._neighbor(index, distance, 0)

    def within_radius(self, query, radius):
        """Exact-scan radius neighbors via the native binding."""
        pairs = self._exact_neighbor_pairs(query, radius=radius)
        if pairs is None:
            _require_native_binding("Space.within_radius(...)", "exact-scan radius search")
        return self._neighbor_result(query, pairs, strategy="exact_range", representation=self.representation)

    def groups(self, strategy=None, *, count="auto", radius=None, min_size=1, representation=None, runtime=None):
        """Group records via clustering (native-only)."""
        _require_native_binding("Space.groups(...)", "clustering")

    def outliers(
        self,
        strategy=None,
        *,
        count=None,
        fraction=0.05,
        threshold=None,
        representation=None,
        runtime=None,
    ):
        """Find unusual records (native-only)."""
        _require_native_binding("Space.outliers(...)", "outlier detection")

    def denoise(
        self,
        strategy=None,
        *,
        count=None,
        fraction=0.05,
        threshold=None,
        strength="auto",
        representation=None,
        runtime=None,
    ):
        """Filter noise records into a derived metric space (native-only)."""
        _require_native_binding("Space.denoise(...)", "density denoising")

    def representatives(self, k=None, strategy=None, *, count=None, representation=None, runtime=None):
        """Select representative records (native-only)."""
        _require_native_binding("Space.representatives(...)", "representative selection")

    def _representation_name(self, representation):
        representation_name = "metric_space"
        if representation is not None:
            representation.ensure_fresh()
            representation_name = getattr(representation, "representation", representation_name)
        return representation_name

    def reduce(self, count=None, strategy=None, *, representation=None, runtime=None):
        """Reduce the space to representative records (native-only)."""
        _require_native_binding("Space.reduce(...)", "representative reduction")

    def compress(self, count=None, strategy=None, *, representation=None, runtime=None):
        """Compress the space by retaining representatives (native-only)."""
        _require_native_binding("Space.compress(...)", "representative compression")

    def map(self, transform=None, metric=None, *, target=None, strategy=None, representation=None, runtime=None):
        require_exact_runtime(runtime)
        from metric.strategies import PhateAE

        if isinstance(strategy, PhateAE):
            if transform is not None or target is not None or metric is not None:
                raise AmbiguousIntentError(
                    "PhateAE native mappings derive their target from the source space; "
                    "omit transform and target, and do not pass a metric"
                )
            if not _is_native_euclidean_vector_metric(self.metric):
                raise StrategyUnavailableError(
                    "Space.map(strategy=PhateAE(...)) only delegates to the native C++ binding for "
                    "Space.vectors(...) values that use the default native-compatible Euclidean vector metric. "
                    "Custom Python metrics are not ignored; use "
                    "metric.mappings.native_phate_autoencoder_fit_vectors(...) explicitly for native Euclidean "
                    "vector rows or stay in C++ for custom metric semantics."
                )

            from metric.mappings import native_phate_autoencoder_fit_vectors
            from metric.operators import MappingResult

            self.ensure_fresh()
            representation_name = self._representation_name(representation)
            model = native_phate_autoencoder_fit_vectors(
                self.records,
                dimensions=strategy.dimensions,
                epochs=strategy.epochs,
                learning_rate=strategy.learning_rate,
                diffusion_steps=strategy.diffusion_steps,
                kernel_scale=1.0 if strategy.kernel_scale is None else strategy.kernel_scale,
                reconstruction_weight=strategy.reconstruction_weight,
                geometry_weight=strategy.geometry_weight,
                seed=strategy.seed,
                distance_provider=strategy.distance_provider,
                affinity_kernel=strategy.affinity_kernel,
                diffusion_operator=strategy.diffusion_operator,
            )
            latent_records = model.transform(self.records)
            latent_space = Space.vectors(
                latent_records,
                ids=self.ids,
                validate="none",
                cache="none",
                metadata={
                    "source_space_version": self.version(),
                    "mapping": model.mapping,
                    "strategy": model.strategy,
                    "distance_provider": model.distance_provider,
                    "affinity_kernel": model.affinity_kernel,
                    "diffusion_operator": model.diffusion_operator,
                },
            )
            source_ids = tuple(self.ids)
            return MappingResult(
                space=latent_space,
                source_record_ids=source_ids,
                source_record_count=len(self.records),
                target_record_count=len(latent_records),
                exact=True,
                operator_name="map",
                mapping=model.mapping,
                strategy=model.strategy,
                representation=representation_name,
                inverse_supported=model.inverse_supported,
                source_records=tuple((record_id,) for record_id in source_ids),
                representative_records=source_ids,
                fitted_model=model,
            )

        if transform is None and target is None:
            raise AmbiguousIntentError("Space.map requires transform=... or target=...")
        if transform is not None and target is not None:
            raise AmbiguousIntentError("Space.map uses either transform or target, not both")
        if strategy is not None:
            raise StrategyUnavailableError(
                "Space.map strategy mappings are not promoted yet. "
                "Use transform=... with metric=... for deterministic maps."
            )
        if target is not None:
            raise StrategyUnavailableError(
                "Space.map target mappings are not promoted yet. "
                "Use transform=... with metric=... for deterministic maps."
            )

        from metric.operators import map_space

        return map_space(
            self.records,
            transform,
            self.metric if metric is None else metric,
            representation=self._representation_name(representation),
        )

    def embed(self, dimensions=2, strategy=None, *, representation=None, runtime=None):
        """Embed the space into Euclidean coordinates (native-only)."""
        _require_native_binding("Space.embed(...)", "metric-space embedding (e.g. classical MDS)")

    def describe(self, *, representation=None, runtime=None):
        """Describe exact finite-space structure (native-only)."""
        _require_native_binding("Space.describe(...)", "structural all-pairs statistics")

    def describe_structure(self, *, representation=None, runtime=None):
        """Describe exact finite-space structure (native-only)."""
        _require_native_binding("Space.describe_structure(...)", "structural all-pairs statistics")

    def runtime_diagnostics(self, *, representation=None, runtime=None, intent=None):
        """Inspect the normalized runtime policy and chosen representation.

        Adapter: this reports policy metadata only; it runs no algorithm.
        """
        from metric.runtime import runtime_diagnostics

        return runtime_diagnostics(
            runtime,
            representation=self._representation_name(representation),
            intent=intent,
        )

    def compare(
        self,
        other,
        strategy=None,
        *,
        align="position",
        other_metric=None,
        representation=None,
        other_representation=None,
        runtime=None,
    ):
        """Compare aligned finite metric spaces (native-only)."""
        _require_native_binding("Space.compare(...)", "cross-space distance-profile correlation")

    def correlate(
        self,
        other,
        strategy=None,
        *,
        align="position",
        other_metric=None,
        representation=None,
        other_representation=None,
        runtime=None,
    ):
        """Correlate aligned finite metric spaces (native-only)."""
        _require_native_binding("Space.correlate(...)", "cross-space distance-profile correlation")


MatrixSpace = FiniteMetricSpace

__all__ = ["FiniteMetricSpace", "MatrixSpace", "Space"]
