// METRIC numeric assimilation header.
// Provenance and licensing are documented in metric/numeric/README.md.

#ifndef METRIC_NUMERIC_UTIL_CONSTRAINTS_CONSTRAINTS_H
#define METRIC_NUMERIC_UTIL_CONSTRAINTS_CONSTRAINTS_H
//=================================================================================================
//
//  DOXYGEN DOCUMENTATION
//
//=================================================================================================

//*************************************************************************************************
/*!\defgroup constraints Compile time constraints
// \ingroup util
//
// Compile time constraints offer the possibility to stop the compilation process if a constraint
// that can be checked at compile time is not met. These constraints are especially useful for
// generic code, where the type of the involved objects is not known beforehands.\n
// Since C++11 the C++ standard provides the \c static_assert functionality to check compile time
// constant expressions:

   \code
   template <class T>
   class RotationMatrix
   {
	  // ...
	  static_assert( std::is_floating_point_v<T>, "Non-floating point type detected" );
	  // ...
   };
   \endcode

// The Metric numeric library extends this functionality in the form of compile time constraint macros:

   \code
   template <class T>
   class RotationMatrix
   {
	  // ...
	  METRIC_NUMERIC_CONSTRAINT_MUST_BE_FLOATING_POINT_TYPE( T );
	  // ...
   };
   \endcode

// The compile time constraints provided by the Metric numeric library built on \c static_assert, but offer
// the additional advantages ...
//
//   - ... of a more convenient and easier usage since details are abstracted;
//   - ... of a more obvious and more explicit way to express compile time constraints;
//   - ... of encapsulation of complex compile time conditions.
//
// The following example demonstrates the \c METRIC_NUMERIC_CONSTRAINT_MUST_BE_DERIVED_FROM time constraint
// and shows a possible error message:

   \code
   //----- Test.cpp -----
   #include <metric/numeric/Util.h>

   class A {};
   class B : public A {};
   class C {};

   int main()
   {
	  METRIC_NUMERIC_CONSTRAINT_MUST_BE_DERIVED_FROM( B, A );  // No compile time error, B is derived from A
	  METRIC_NUMERIC_CONSTRAINT_MUST_BE_DERIVED_FROM( C, A );  // Compile time error, C is not derived from A
   }
   \endcode

// The resulting error message generated by the GNU g++ compiler contains the name of the
// constraint, a descriptive error message and the source code line of the constraint violation:

   \code
   ~/metric/numeric/metric/numeric/util/constraints/DerivedFrom.h:61:4: static assertion failed: Broken inheritance
hierarchy detected static_assert( ::mtrc::numeric::IsBaseOf_v<B,D>, "Broken inheritance hierarchy detected" )
	  ^
   Test.cpp:11:4: note: in expansion of macro 'METRIC_NUMERIC_CONSTRAINT_MUST_BE_DERIVED_FROM'
	  METRIC_NUMERIC_CONSTRAINT_MUST_BE_DERIVED_FROM( C, A );  // Compile time error, C is not derived from A
   \endcode
*/
//*************************************************************************************************

#endif
