// METRIC numeric assimilation header.
// Provenance and licensing are documented in metric/numeric/README.md.

#ifndef METRIC_NUMERIC_MATH_CONSTRAINTS_H
#define METRIC_NUMERIC_MATH_CONSTRAINTS_H
//*************************************************************************************************
// Includes
//*************************************************************************************************

#include <metric/numeric/math/constraints/Adaptor.h>
#include <metric/numeric/math/constraints/AddExpr.h>
#include <metric/numeric/math/constraints/Aligned.h>
#include <metric/numeric/math/constraints/BLASCompatible.h>
#include <metric/numeric/math/constraints/Band.h>
#include <metric/numeric/math/constraints/BinaryMapExpr.h>
#include <metric/numeric/math/constraints/CUDAAssignable.h>
#include <metric/numeric/math/constraints/Clearable.h>
#include <metric/numeric/math/constraints/Column.h>
#include <metric/numeric/math/constraints/ColumnMajorMatrix.h>
#include <metric/numeric/math/constraints/ColumnVector.h>
#include <metric/numeric/math/constraints/Columns.h>
#include <metric/numeric/math/constraints/Commutative.h>
#include <metric/numeric/math/constraints/CompositeType.h>
#include <metric/numeric/math/constraints/Computation.h>
#include <metric/numeric/math/constraints/ConstDataAccess.h>
#include <metric/numeric/math/constraints/Contiguous.h>
#include <metric/numeric/math/constraints/CrossExpr.h>
#include <metric/numeric/math/constraints/Custom.h>
#include <metric/numeric/math/constraints/DeclDiagExpr.h>
#include <metric/numeric/math/constraints/DeclExpr.h>
#include <metric/numeric/math/constraints/DeclHermExpr.h>
#include <metric/numeric/math/constraints/DeclLowExpr.h>
#include <metric/numeric/math/constraints/DeclStrLowExpr.h>
#include <metric/numeric/math/constraints/DeclStrUppExpr.h>
#include <metric/numeric/math/constraints/DeclSymExpr.h>
#include <metric/numeric/math/constraints/DeclUniLowExpr.h>
#include <metric/numeric/math/constraints/DeclUniUppExpr.h>
#include <metric/numeric/math/constraints/DeclUppExpr.h>
#include <metric/numeric/math/constraints/Declaration.h>
#include <metric/numeric/math/constraints/DenseMatrix.h>
#include <metric/numeric/math/constraints/DenseVector.h>
#include <metric/numeric/math/constraints/Diagonal.h>
#include <metric/numeric/math/constraints/DivExpr.h>
#include <metric/numeric/math/constraints/EigenExpr.h>
#include <metric/numeric/math/constraints/Elements.h>
#include <metric/numeric/math/constraints/EvalExpr.h>
#include <metric/numeric/math/constraints/ExpandExpr.h>
#include <metric/numeric/math/constraints/Expression.h>
#include <metric/numeric/math/constraints/GenExpr.h>
#include <metric/numeric/math/constraints/General.h>
#include <metric/numeric/math/constraints/Hermitian.h>
#include <metric/numeric/math/constraints/Identity.h>
#include <metric/numeric/math/constraints/Initializer.h>
#include <metric/numeric/math/constraints/Invertible.h>
#include <metric/numeric/math/constraints/KronExpr.h>
#include <metric/numeric/math/constraints/Lower.h>
#include <metric/numeric/math/constraints/MatEvalExpr.h>
#include <metric/numeric/math/constraints/MatExpExpr.h>
#include <metric/numeric/math/constraints/MatGenExpr.h>
#include <metric/numeric/math/constraints/MatInvExpr.h>
#include <metric/numeric/math/constraints/MatMapExpr.h>
#include <metric/numeric/math/constraints/MatMatAddExpr.h>
#include <metric/numeric/math/constraints/MatMatKronExpr.h>
#include <metric/numeric/math/constraints/MatMatMapExpr.h>
#include <metric/numeric/math/constraints/MatMatMultExpr.h>
#include <metric/numeric/math/constraints/MatMatSolveExpr.h>
#include <metric/numeric/math/constraints/MatMatSubExpr.h>
#include <metric/numeric/math/constraints/MatNoAliasExpr.h>
#include <metric/numeric/math/constraints/MatNoSIMDExpr.h>
#include <metric/numeric/math/constraints/MatReduceExpr.h>
#include <metric/numeric/math/constraints/MatRepeatExpr.h>
#include <metric/numeric/math/constraints/MatScalarDivExpr.h>
#include <metric/numeric/math/constraints/MatScalarMultExpr.h>
#include <metric/numeric/math/constraints/MatSerialExpr.h>
#include <metric/numeric/math/constraints/MatTransExpr.h>
#include <metric/numeric/math/constraints/MatVecMultExpr.h>
#include <metric/numeric/math/constraints/MatVecSolveExpr.h>
#include <metric/numeric/math/constraints/Matrix.h>
#include <metric/numeric/math/constraints/Modification.h>
#include <metric/numeric/math/constraints/MultExpr.h>
#include <metric/numeric/math/constraints/MutableDataAccess.h>
#include <metric/numeric/math/constraints/NoAliasExpr.h>
#include <metric/numeric/math/constraints/NoSIMDExpr.h>
#include <metric/numeric/math/constraints/Operation.h>
#include <metric/numeric/math/constraints/OpposedView.h>
#include <metric/numeric/math/constraints/Padded.h>
#include <metric/numeric/math/constraints/PaddingEnabled.h>
#include <metric/numeric/math/constraints/Proxy.h>
#include <metric/numeric/math/constraints/ReduceExpr.h>
#include <metric/numeric/math/constraints/RepeatExpr.h>
#include <metric/numeric/math/constraints/RequiresEvaluation.h>
#include <metric/numeric/math/constraints/Resizable.h>
#include <metric/numeric/math/constraints/Restricted.h>
#include <metric/numeric/math/constraints/ResultType.h>
#include <metric/numeric/math/constraints/Row.h>
#include <metric/numeric/math/constraints/RowMajorMatrix.h>
#include <metric/numeric/math/constraints/RowVector.h>
#include <metric/numeric/math/constraints/Rows.h>
#include <metric/numeric/math/constraints/SIMDCombinable.h>
#include <metric/numeric/math/constraints/SIMDEnabled.h>
#include <metric/numeric/math/constraints/SIMDPack.h>
#include <metric/numeric/math/constraints/SMPAssignable.h>
#include <metric/numeric/math/constraints/SVDExpr.h>
#include <metric/numeric/math/constraints/SameTag.h>
#include <metric/numeric/math/constraints/Scalar.h>
#include <metric/numeric/math/constraints/SchurExpr.h>
#include <metric/numeric/math/constraints/SerialExpr.h>
#include <metric/numeric/math/constraints/Shrinkable.h>
#include <metric/numeric/math/constraints/SolveExpr.h>
#include <metric/numeric/math/constraints/SparseElement.h>
#include <metric/numeric/math/constraints/SparseMatrix.h>
#include <metric/numeric/math/constraints/SparseVector.h>
#include <metric/numeric/math/constraints/Square.h>
#include <metric/numeric/math/constraints/Static.h>
#include <metric/numeric/math/constraints/StorageOrder.h>
#include <metric/numeric/math/constraints/StrictlyLower.h>
#include <metric/numeric/math/constraints/StrictlyTriangular.h>
#include <metric/numeric/math/constraints/StrictlyUpper.h>
#include <metric/numeric/math/constraints/SubExpr.h>
#include <metric/numeric/math/constraints/Submatrix.h>
#include <metric/numeric/math/constraints/Subvector.h>
#include <metric/numeric/math/constraints/Symmetric.h>
#include <metric/numeric/math/constraints/TVecMatMultExpr.h>
#include <metric/numeric/math/constraints/TransExpr.h>
#include <metric/numeric/math/constraints/Transformation.h>
#include <metric/numeric/math/constraints/TransposeFlag.h>
#include <metric/numeric/math/constraints/Triangular.h>
#include <metric/numeric/math/constraints/UnaryMapExpr.h>
#include <metric/numeric/math/constraints/UniLower.h>
#include <metric/numeric/math/constraints/UniTriangular.h>
#include <metric/numeric/math/constraints/UniUpper.h>
#include <metric/numeric/math/constraints/Uniform.h>
#include <metric/numeric/math/constraints/Upper.h>
#include <metric/numeric/math/constraints/VecEvalExpr.h>
#include <metric/numeric/math/constraints/VecExpandExpr.h>
#include <metric/numeric/math/constraints/VecGenExpr.h>
#include <metric/numeric/math/constraints/VecMapExpr.h>
#include <metric/numeric/math/constraints/VecNoAliasExpr.h>
#include <metric/numeric/math/constraints/VecNoSIMDExpr.h>
#include <metric/numeric/math/constraints/VecRepeatExpr.h>
#include <metric/numeric/math/constraints/VecScalarDivExpr.h>
#include <metric/numeric/math/constraints/VecScalarMultExpr.h>
#include <metric/numeric/math/constraints/VecSerialExpr.h>
#include <metric/numeric/math/constraints/VecTVecMapExpr.h>
#include <metric/numeric/math/constraints/VecTVecMultExpr.h>
#include <metric/numeric/math/constraints/VecTransExpr.h>
#include <metric/numeric/math/constraints/VecVecAddExpr.h>
#include <metric/numeric/math/constraints/VecVecDivExpr.h>
#include <metric/numeric/math/constraints/VecVecKronExpr.h>
#include <metric/numeric/math/constraints/VecVecMapExpr.h>
#include <metric/numeric/math/constraints/VecVecMultExpr.h>
#include <metric/numeric/math/constraints/VecVecSubExpr.h>
#include <metric/numeric/math/constraints/Vector.h>
#include <metric/numeric/math/constraints/View.h>
#include <metric/numeric/math/constraints/Zero.h>

#endif
