// METRIC numeric assimilation header.
// Provenance and licensing are documented in metric/numeric/README.md.

#ifndef METRIC_NUMERIC_MATH_DENSEMATRIX_H
#define METRIC_NUMERIC_MATH_DENSEMATRIX_H
//*************************************************************************************************
// Includes
//*************************************************************************************************

#include <metric/numeric/math/Matrix.h>
#include <metric/numeric/math/adaptors/DiagonalMatrix.h>
#include <metric/numeric/math/adaptors/HermitianMatrix.h>
#include <metric/numeric/math/adaptors/LowerMatrix.h>
#include <metric/numeric/math/adaptors/SymmetricMatrix.h>
#include <metric/numeric/math/adaptors/UpperMatrix.h>
#include <metric/numeric/math/dense/DenseMatrix.h>
#include <metric/numeric/math/dense/Eigen.h>
#include <metric/numeric/math/dense/Inversion.h>
#include <metric/numeric/math/dense/LLH.h>
#include <metric/numeric/math/dense/LQ.h>
#include <metric/numeric/math/dense/LSE.h>
#include <metric/numeric/math/dense/LU.h>
#include <metric/numeric/math/dense/PLLHP.h>
#include <metric/numeric/math/dense/QL.h>
#include <metric/numeric/math/dense/QR.h>
#include <metric/numeric/math/dense/RQ.h>
#include <metric/numeric/math/dense/SVD.h>
#include <metric/numeric/math/expressions/DMatDMatAddExpr.h>
#include <metric/numeric/math/expressions/DMatDMatEqualExpr.h>
#include <metric/numeric/math/expressions/DMatDMatKronExpr.h>
#include <metric/numeric/math/expressions/DMatDMatMapExpr.h>
#include <metric/numeric/math/expressions/DMatDMatMultExpr.h>
#include <metric/numeric/math/expressions/DMatDMatSchurExpr.h>
#include <metric/numeric/math/expressions/DMatDMatSolveExpr.h>
#include <metric/numeric/math/expressions/DMatDMatSubExpr.h>
#include <metric/numeric/math/expressions/DMatDVecMultExpr.h>
#include <metric/numeric/math/expressions/DMatDVecSolveExpr.h>
#include <metric/numeric/math/expressions/DMatDeclDiagExpr.h>
#include <metric/numeric/math/expressions/DMatDeclHermExpr.h>
#include <metric/numeric/math/expressions/DMatDeclLowExpr.h>
#include <metric/numeric/math/expressions/DMatDeclStrLowExpr.h>
#include <metric/numeric/math/expressions/DMatDeclStrUppExpr.h>
#include <metric/numeric/math/expressions/DMatDeclSymExpr.h>
#include <metric/numeric/math/expressions/DMatDeclUniLowExpr.h>
#include <metric/numeric/math/expressions/DMatDeclUniUppExpr.h>
#include <metric/numeric/math/expressions/DMatDeclUppExpr.h>
#include <metric/numeric/math/expressions/DMatDetExpr.h>
#include <metric/numeric/math/expressions/DMatEigenExpr.h>
#include <metric/numeric/math/expressions/DMatEvalExpr.h>
#include <metric/numeric/math/expressions/DMatExpExpr.h>
#include <metric/numeric/math/expressions/DMatFixExpr.h>
#include <metric/numeric/math/expressions/DMatGenExpr.h>
#include <metric/numeric/math/expressions/DMatInvExpr.h>
#include <metric/numeric/math/expressions/DMatMapExpr.h>
#include <metric/numeric/math/expressions/DMatMeanExpr.h>
#include <metric/numeric/math/expressions/DMatNoAliasExpr.h>
#include <metric/numeric/math/expressions/DMatNoSIMDExpr.h>
#include <metric/numeric/math/expressions/DMatNormExpr.h>
#include <metric/numeric/math/expressions/DMatReduceExpr.h>
#include <metric/numeric/math/expressions/DMatRepeatExpr.h>
#include <metric/numeric/math/expressions/DMatSMatAddExpr.h>
#include <metric/numeric/math/expressions/DMatSMatMultExpr.h>
#include <metric/numeric/math/expressions/DMatSMatSubExpr.h>
#include <metric/numeric/math/expressions/DMatSVDExpr.h>
#include <metric/numeric/math/expressions/DMatSVecMultExpr.h>
#include <metric/numeric/math/expressions/DMatScalarDivExpr.h>
#include <metric/numeric/math/expressions/DMatScalarMultExpr.h>
#include <metric/numeric/math/expressions/DMatSerialExpr.h>
#include <metric/numeric/math/expressions/DMatSoftmaxExpr.h>
#include <metric/numeric/math/expressions/DMatStdDevExpr.h>
#include <metric/numeric/math/expressions/DMatTDMatAddExpr.h>
#include <metric/numeric/math/expressions/DMatTDMatMapExpr.h>
#include <metric/numeric/math/expressions/DMatTDMatMultExpr.h>
#include <metric/numeric/math/expressions/DMatTDMatSchurExpr.h>
#include <metric/numeric/math/expressions/DMatTDMatSubExpr.h>
#include <metric/numeric/math/expressions/DMatTSMatAddExpr.h>
#include <metric/numeric/math/expressions/DMatTSMatMultExpr.h>
#include <metric/numeric/math/expressions/DMatTSMatSubExpr.h>
#include <metric/numeric/math/expressions/DMatTransExpr.h>
#include <metric/numeric/math/expressions/DMatVarExpr.h>
#include <metric/numeric/math/expressions/DVecDVecOuterExpr.h>
#include <metric/numeric/math/expressions/DenseMatrix.h>
#include <metric/numeric/math/expressions/SMatDMatMultExpr.h>
#include <metric/numeric/math/expressions/SMatDMatSubExpr.h>
#include <metric/numeric/math/expressions/SMatTDMatMultExpr.h>
#include <metric/numeric/math/expressions/SMatTDMatSubExpr.h>
#include <metric/numeric/math/expressions/SparseMatrix.h>
#include <metric/numeric/math/expressions/TDMatDMatMultExpr.h>
#include <metric/numeric/math/expressions/TDMatDVecMultExpr.h>
#include <metric/numeric/math/expressions/TDMatSMatAddExpr.h>
#include <metric/numeric/math/expressions/TDMatSMatMultExpr.h>
#include <metric/numeric/math/expressions/TDMatSMatSubExpr.h>
#include <metric/numeric/math/expressions/TDMatSVecMultExpr.h>
#include <metric/numeric/math/expressions/TDMatTDMatMultExpr.h>
#include <metric/numeric/math/expressions/TDMatTSMatMultExpr.h>
#include <metric/numeric/math/expressions/TDVecDMatMultExpr.h>
#include <metric/numeric/math/expressions/TDVecTDMatMultExpr.h>
#include <metric/numeric/math/expressions/TSMatDMatMultExpr.h>
#include <metric/numeric/math/expressions/TSMatDMatSubExpr.h>
#include <metric/numeric/math/expressions/TSMatTDMatMultExpr.h>
#include <metric/numeric/math/expressions/TSVecDMatMultExpr.h>
#include <metric/numeric/math/expressions/TSVecTDMatMultExpr.h>
#include <metric/numeric/math/serialization/MatrixSerializer.h>
#include <metric/numeric/math/smp/DenseMatrix.h>
#include <metric/numeric/math/smp/SparseMatrix.h>
#include <metric/numeric/math/views/Column.h>
#include <metric/numeric/math/views/Row.h>
#include <metric/numeric/math/views/Submatrix.h>
#include <metric/numeric/math/views/Subvector.h>

#endif
