// METRIC numeric assimilation header.
// Provenance and licensing are documented in metric/numeric/README.md.

#ifndef METRIC_NUMERIC_MATH_FUNCTORS_H
#define METRIC_NUMERIC_MATH_FUNCTORS_H
//*************************************************************************************************
// Includes
//*************************************************************************************************

#include <metric/numeric/math/functors/Abs.h>
#include <metric/numeric/math/functors/Acos.h>
#include <metric/numeric/math/functors/Acosh.h>
#include <metric/numeric/math/functors/Add.h>
#include <metric/numeric/math/functors/AddAssign.h>
#include <metric/numeric/math/functors/And.h>
#include <metric/numeric/math/functors/AndAssign.h>
#include <metric/numeric/math/functors/Arg.h>
#include <metric/numeric/math/functors/Asin.h>
#include <metric/numeric/math/functors/Asinh.h>
#include <metric/numeric/math/functors/Assign.h>
#include <metric/numeric/math/functors/Atan.h>
#include <metric/numeric/math/functors/Atan2.h>
#include <metric/numeric/math/functors/Atanh.h>
#include <metric/numeric/math/functors/Bind1st.h>
#include <metric/numeric/math/functors/Bind2nd.h>
#include <metric/numeric/math/functors/Bind3rd.h>
#include <metric/numeric/math/functors/Bitand.h>
#include <metric/numeric/math/functors/Bitor.h>
#include <metric/numeric/math/functors/Bitxor.h>
#include <metric/numeric/math/functors/CTrans.h>
#include <metric/numeric/math/functors/Cbrt.h>
#include <metric/numeric/math/functors/Ceil.h>
#include <metric/numeric/math/functors/Clamp.h>
#include <metric/numeric/math/functors/Clear.h>
#include <metric/numeric/math/functors/Conj.h>
#include <metric/numeric/math/functors/Cos.h>
#include <metric/numeric/math/functors/Cosh.h>
#include <metric/numeric/math/functors/DeclDiag.h>
#include <metric/numeric/math/functors/DeclHerm.h>
#include <metric/numeric/math/functors/DeclId.h>
#include <metric/numeric/math/functors/DeclLow.h>
#include <metric/numeric/math/functors/DeclStrLow.h>
#include <metric/numeric/math/functors/DeclStrUpp.h>
#include <metric/numeric/math/functors/DeclSym.h>
#include <metric/numeric/math/functors/DeclUniLow.h>
#include <metric/numeric/math/functors/DeclUniUpp.h>
#include <metric/numeric/math/functors/DeclUpp.h>
#include <metric/numeric/math/functors/DeclZero.h>
#include <metric/numeric/math/functors/Div.h>
#include <metric/numeric/math/functors/DivAssign.h>
#include <metric/numeric/math/functors/Erf.h>
#include <metric/numeric/math/functors/Erfc.h>
#include <metric/numeric/math/functors/Eval.h>
#include <metric/numeric/math/functors/Exp.h>
#include <metric/numeric/math/functors/Exp10.h>
#include <metric/numeric/math/functors/Exp2.h>
#include <metric/numeric/math/functors/Floor.h>
#include <metric/numeric/math/functors/Greater.h>
#include <metric/numeric/math/functors/Hypot.h>
#include <metric/numeric/math/functors/Imag.h>
#include <metric/numeric/math/functors/Inv.h>
#include <metric/numeric/math/functors/InvAdd.h>
#include <metric/numeric/math/functors/InvCbrt.h>
#include <metric/numeric/math/functors/InvSqrt.h>
#include <metric/numeric/math/functors/Join.h>
#include <metric/numeric/math/functors/Kron.h>
#include <metric/numeric/math/functors/L1Norm.h>
#include <metric/numeric/math/functors/L2Norm.h>
#include <metric/numeric/math/functors/L3Norm.h>
#include <metric/numeric/math/functors/L4Norm.h>
#include <metric/numeric/math/functors/LGamma.h>
#include <metric/numeric/math/functors/LeftShiftAssign.h>
#include <metric/numeric/math/functors/Less.h>
#include <metric/numeric/math/functors/Log.h>
#include <metric/numeric/math/functors/Log10.h>
#include <metric/numeric/math/functors/Log1p.h>
#include <metric/numeric/math/functors/Log2.h>
#include <metric/numeric/math/functors/LpNorm.h>
#include <metric/numeric/math/functors/MAC.h>
#include <metric/numeric/math/functors/MakePair.h>
#include <metric/numeric/math/functors/Max.h>
#include <metric/numeric/math/functors/Min.h>
#include <metric/numeric/math/functors/Minmax.h>
#include <metric/numeric/math/functors/ModuloAssign.h>
#include <metric/numeric/math/functors/Mult.h>
#include <metric/numeric/math/functors/MultAssign.h>
#include <metric/numeric/math/functors/NoAlias.h>
#include <metric/numeric/math/functors/NoSIMD.h>
#include <metric/numeric/math/functors/Noop.h>
#include <metric/numeric/math/functors/Not.h>
#include <metric/numeric/math/functors/Or.h>
#include <metric/numeric/math/functors/OrAssign.h>
#include <metric/numeric/math/functors/Pow.h>
#include <metric/numeric/math/functors/Pow2.h>
#include <metric/numeric/math/functors/Pow3.h>
#include <metric/numeric/math/functors/Pow4.h>
#include <metric/numeric/math/functors/Qdrt.h>
#include <metric/numeric/math/functors/Real.h>
#include <metric/numeric/math/functors/Reset.h>
#include <metric/numeric/math/functors/RightShiftAssign.h>
#include <metric/numeric/math/functors/Round.h>
#include <metric/numeric/math/functors/Schur.h>
#include <metric/numeric/math/functors/Serial.h>
#include <metric/numeric/math/functors/ShiftLI.h>
#include <metric/numeric/math/functors/ShiftLV.h>
#include <metric/numeric/math/functors/ShiftRI.h>
#include <metric/numeric/math/functors/ShiftRV.h>
#include <metric/numeric/math/functors/Sign.h>
#include <metric/numeric/math/functors/Sin.h>
#include <metric/numeric/math/functors/Sinh.h>
#include <metric/numeric/math/functors/SqrAbs.h>
#include <metric/numeric/math/functors/Sqrt.h>
#include <metric/numeric/math/functors/Sub.h>
#include <metric/numeric/math/functors/SubAssign.h>
#include <metric/numeric/math/functors/Tan.h>
#include <metric/numeric/math/functors/Tanh.h>
#include <metric/numeric/math/functors/Trans.h>
#include <metric/numeric/math/functors/Trunc.h>
#include <metric/numeric/math/functors/XorAssign.h>

#endif
