// METRIC numeric assimilation header.
// Provenance and licensing are documented in metric/numeric/README.md.

#ifndef METRIC_NUMERIC_MATH_TYPETRAITS_H
#define METRIC_NUMERIC_MATH_TYPETRAITS_H
//*************************************************************************************************
// Includes
//*************************************************************************************************

#include <metric/numeric/math/typetraits/CustomOppositeType.h>
#include <metric/numeric/math/typetraits/CustomTransposeType.h>
#include <metric/numeric/math/typetraits/DynamicAllocator.h>
#include <metric/numeric/math/typetraits/GetAllocator.h>
#include <metric/numeric/math/typetraits/HasAbs.h>
#include <metric/numeric/math/typetraits/HasAcos.h>
#include <metric/numeric/math/typetraits/HasAcosh.h>
#include <metric/numeric/math/typetraits/HasAdd.h>
#include <metric/numeric/math/typetraits/HasAsin.h>
#include <metric/numeric/math/typetraits/HasAsinh.h>
#include <metric/numeric/math/typetraits/HasAtan.h>
#include <metric/numeric/math/typetraits/HasAtan2.h>
#include <metric/numeric/math/typetraits/HasAtanh.h>
#include <metric/numeric/math/typetraits/HasCbrt.h>
#include <metric/numeric/math/typetraits/HasCeil.h>
#include <metric/numeric/math/typetraits/HasClamp.h>
#include <metric/numeric/math/typetraits/HasCompositeType.h>
#include <metric/numeric/math/typetraits/HasConj.h>
#include <metric/numeric/math/typetraits/HasConstDataAccess.h>
#include <metric/numeric/math/typetraits/HasCos.h>
#include <metric/numeric/math/typetraits/HasCosh.h>
#include <metric/numeric/math/typetraits/HasDiv.h>
#include <metric/numeric/math/typetraits/HasErf.h>
#include <metric/numeric/math/typetraits/HasErfc.h>
#include <metric/numeric/math/typetraits/HasExp.h>
#include <metric/numeric/math/typetraits/HasExp10.h>
#include <metric/numeric/math/typetraits/HasExp2.h>
#include <metric/numeric/math/typetraits/HasFloor.h>
#include <metric/numeric/math/typetraits/HasHypot.h>
#include <metric/numeric/math/typetraits/HasImag.h>
#include <metric/numeric/math/typetraits/HasInvCbrt.h>
#include <metric/numeric/math/typetraits/HasInvSqrt.h>
#include <metric/numeric/math/typetraits/HasLGamma.h>
#include <metric/numeric/math/typetraits/HasLoad.h>
#include <metric/numeric/math/typetraits/HasLog.h>
#include <metric/numeric/math/typetraits/HasLog10.h>
#include <metric/numeric/math/typetraits/HasLog1p.h>
#include <metric/numeric/math/typetraits/HasLog2.h>
#include <metric/numeric/math/typetraits/HasMax.h>
#include <metric/numeric/math/typetraits/HasMin.h>
#include <metric/numeric/math/typetraits/HasMult.h>
#include <metric/numeric/math/typetraits/HasMutableDataAccess.h>
#include <metric/numeric/math/typetraits/HasPow.h>
#include <metric/numeric/math/typetraits/HasReal.h>
#include <metric/numeric/math/typetraits/HasResultType.h>
#include <metric/numeric/math/typetraits/HasRound.h>
#include <metric/numeric/math/typetraits/HasSIMDAbs.h>
#include <metric/numeric/math/typetraits/HasSIMDAcos.h>
#include <metric/numeric/math/typetraits/HasSIMDAcosh.h>
#include <metric/numeric/math/typetraits/HasSIMDAdd.h>
#include <metric/numeric/math/typetraits/HasSIMDAsin.h>
#include <metric/numeric/math/typetraits/HasSIMDAsinh.h>
#include <metric/numeric/math/typetraits/HasSIMDAtan.h>
#include <metric/numeric/math/typetraits/HasSIMDAtan2.h>
#include <metric/numeric/math/typetraits/HasSIMDAtanh.h>
#include <metric/numeric/math/typetraits/HasSIMDBitand.h>
#include <metric/numeric/math/typetraits/HasSIMDBitor.h>
#include <metric/numeric/math/typetraits/HasSIMDBitxor.h>
#include <metric/numeric/math/typetraits/HasSIMDCbrt.h>
#include <metric/numeric/math/typetraits/HasSIMDCeil.h>
#include <metric/numeric/math/typetraits/HasSIMDConj.h>
#include <metric/numeric/math/typetraits/HasSIMDCos.h>
#include <metric/numeric/math/typetraits/HasSIMDCosh.h>
#include <metric/numeric/math/typetraits/HasSIMDDiv.h>
#include <metric/numeric/math/typetraits/HasSIMDEqual.h>
#include <metric/numeric/math/typetraits/HasSIMDErf.h>
#include <metric/numeric/math/typetraits/HasSIMDErfc.h>
#include <metric/numeric/math/typetraits/HasSIMDExp.h>
#include <metric/numeric/math/typetraits/HasSIMDExp10.h>
#include <metric/numeric/math/typetraits/HasSIMDExp2.h>
#include <metric/numeric/math/typetraits/HasSIMDFloor.h>
#include <metric/numeric/math/typetraits/HasSIMDHypot.h>
#include <metric/numeric/math/typetraits/HasSIMDInvCbrt.h>
#include <metric/numeric/math/typetraits/HasSIMDInvSqrt.h>
#include <metric/numeric/math/typetraits/HasSIMDLGamma.h>
#include <metric/numeric/math/typetraits/HasSIMDLog.h>
#include <metric/numeric/math/typetraits/HasSIMDLog10.h>
#include <metric/numeric/math/typetraits/HasSIMDLog1p.h>
#include <metric/numeric/math/typetraits/HasSIMDLog2.h>
#include <metric/numeric/math/typetraits/HasSIMDMax.h>
#include <metric/numeric/math/typetraits/HasSIMDMin.h>
#include <metric/numeric/math/typetraits/HasSIMDMult.h>
#include <metric/numeric/math/typetraits/HasSIMDPow.h>
#include <metric/numeric/math/typetraits/HasSIMDRound.h>
#include <metric/numeric/math/typetraits/HasSIMDShiftLI.h>
#include <metric/numeric/math/typetraits/HasSIMDShiftLV.h>
#include <metric/numeric/math/typetraits/HasSIMDShiftRI.h>
#include <metric/numeric/math/typetraits/HasSIMDShiftRV.h>
#include <metric/numeric/math/typetraits/HasSIMDSign.h>
#include <metric/numeric/math/typetraits/HasSIMDSin.h>
#include <metric/numeric/math/typetraits/HasSIMDSinh.h>
#include <metric/numeric/math/typetraits/HasSIMDSqrt.h>
#include <metric/numeric/math/typetraits/HasSIMDSub.h>
#include <metric/numeric/math/typetraits/HasSIMDTan.h>
#include <metric/numeric/math/typetraits/HasSIMDTanh.h>
#include <metric/numeric/math/typetraits/HasSIMDTrunc.h>
#include <metric/numeric/math/typetraits/HasSign.h>
#include <metric/numeric/math/typetraits/HasSin.h>
#include <metric/numeric/math/typetraits/HasSinh.h>
#include <metric/numeric/math/typetraits/HasSqrt.h>
#include <metric/numeric/math/typetraits/HasSub.h>
#include <metric/numeric/math/typetraits/HasTan.h>
#include <metric/numeric/math/typetraits/HasTanh.h>
#include <metric/numeric/math/typetraits/HasTrunc.h>
#include <metric/numeric/math/typetraits/HighType.h>
#include <metric/numeric/math/typetraits/IsAdaptor.h>
#include <metric/numeric/math/typetraits/IsAddExpr.h>
#include <metric/numeric/math/typetraits/IsAligned.h>
#include <metric/numeric/math/typetraits/IsBLASCompatible.h>
#include <metric/numeric/math/typetraits/IsBand.h>
#include <metric/numeric/math/typetraits/IsBinaryMapExpr.h>
#include <metric/numeric/math/typetraits/IsCUDAAssignable.h>
#include <metric/numeric/math/typetraits/IsClearable.h>
#include <metric/numeric/math/typetraits/IsColumn.h>
#include <metric/numeric/math/typetraits/IsColumnMajorMatrix.h>
#include <metric/numeric/math/typetraits/IsColumnVector.h>
#include <metric/numeric/math/typetraits/IsColumns.h>
#include <metric/numeric/math/typetraits/IsCommutative.h>
#include <metric/numeric/math/typetraits/IsComputation.h>
#include <metric/numeric/math/typetraits/IsContiguous.h>
#include <metric/numeric/math/typetraits/IsCrossExpr.h>
#include <metric/numeric/math/typetraits/IsCustom.h>
#include <metric/numeric/math/typetraits/IsDeclDiagExpr.h>
#include <metric/numeric/math/typetraits/IsDeclExpr.h>
#include <metric/numeric/math/typetraits/IsDeclHermExpr.h>
#include <metric/numeric/math/typetraits/IsDeclLowExpr.h>
#include <metric/numeric/math/typetraits/IsDeclStrLowExpr.h>
#include <metric/numeric/math/typetraits/IsDeclStrUppExpr.h>
#include <metric/numeric/math/typetraits/IsDeclSymExpr.h>
#include <metric/numeric/math/typetraits/IsDeclUniLowExpr.h>
#include <metric/numeric/math/typetraits/IsDeclUniUppExpr.h>
#include <metric/numeric/math/typetraits/IsDeclUppExpr.h>
#include <metric/numeric/math/typetraits/IsDeclaration.h>
#include <metric/numeric/math/typetraits/IsDenseMatrix.h>
#include <metric/numeric/math/typetraits/IsDenseVector.h>
#include <metric/numeric/math/typetraits/IsDiagonal.h>
#include <metric/numeric/math/typetraits/IsDivExpr.h>
#include <metric/numeric/math/typetraits/IsEigenExpr.h>
#include <metric/numeric/math/typetraits/IsElements.h>
#include <metric/numeric/math/typetraits/IsEvalExpr.h>
#include <metric/numeric/math/typetraits/IsExpandExpr.h>
#include <metric/numeric/math/typetraits/IsExpression.h>
#include <metric/numeric/math/typetraits/IsGenExpr.h>
#include <metric/numeric/math/typetraits/IsGeneral.h>
#include <metric/numeric/math/typetraits/IsHermitian.h>
#include <metric/numeric/math/typetraits/IsIdentity.h>
#include <metric/numeric/math/typetraits/IsInitializer.h>
#include <metric/numeric/math/typetraits/IsInvertible.h>
#include <metric/numeric/math/typetraits/IsKronExpr.h>
#include <metric/numeric/math/typetraits/IsLower.h>
#include <metric/numeric/math/typetraits/IsMatEvalExpr.h>
#include <metric/numeric/math/typetraits/IsMatExpExpr.h>
#include <metric/numeric/math/typetraits/IsMatGenExpr.h>
#include <metric/numeric/math/typetraits/IsMatInvExpr.h>
#include <metric/numeric/math/typetraits/IsMatMapExpr.h>
#include <metric/numeric/math/typetraits/IsMatMatAddExpr.h>
#include <metric/numeric/math/typetraits/IsMatMatKronExpr.h>
#include <metric/numeric/math/typetraits/IsMatMatMapExpr.h>
#include <metric/numeric/math/typetraits/IsMatMatMultExpr.h>
#include <metric/numeric/math/typetraits/IsMatMatSolveExpr.h>
#include <metric/numeric/math/typetraits/IsMatMatSubExpr.h>
#include <metric/numeric/math/typetraits/IsMatNoAliasExpr.h>
#include <metric/numeric/math/typetraits/IsMatNoSIMDExpr.h>
#include <metric/numeric/math/typetraits/IsMatReduceExpr.h>
#include <metric/numeric/math/typetraits/IsMatRepeatExpr.h>
#include <metric/numeric/math/typetraits/IsMatScalarDivExpr.h>
#include <metric/numeric/math/typetraits/IsMatScalarMultExpr.h>
#include <metric/numeric/math/typetraits/IsMatSerialExpr.h>
#include <metric/numeric/math/typetraits/IsMatTransExpr.h>
#include <metric/numeric/math/typetraits/IsMatVecMultExpr.h>
#include <metric/numeric/math/typetraits/IsMatVecSolveExpr.h>
#include <metric/numeric/math/typetraits/IsMatrix.h>
#include <metric/numeric/math/typetraits/IsModification.h>
#include <metric/numeric/math/typetraits/IsMultExpr.h>
#include <metric/numeric/math/typetraits/IsNoAliasExpr.h>
#include <metric/numeric/math/typetraits/IsNoSIMDExpr.h>
#include <metric/numeric/math/typetraits/IsOperation.h>
#include <metric/numeric/math/typetraits/IsOpposedView.h>
#include <metric/numeric/math/typetraits/IsPadded.h>
#include <metric/numeric/math/typetraits/IsPaddingEnabled.h>
#include <metric/numeric/math/typetraits/IsProxy.h>
#include <metric/numeric/math/typetraits/IsReduceExpr.h>
#include <metric/numeric/math/typetraits/IsRepeatExpr.h>
#include <metric/numeric/math/typetraits/IsResizable.h>
#include <metric/numeric/math/typetraits/IsRestricted.h>
#include <metric/numeric/math/typetraits/IsRow.h>
#include <metric/numeric/math/typetraits/IsRowMajorMatrix.h>
#include <metric/numeric/math/typetraits/IsRowVector.h>
#include <metric/numeric/math/typetraits/IsRows.h>
#include <metric/numeric/math/typetraits/IsSIMDCombinable.h>
#include <metric/numeric/math/typetraits/IsSIMDEnabled.h>
#include <metric/numeric/math/typetraits/IsSIMDPack.h>
#include <metric/numeric/math/typetraits/IsSMPAssignable.h>
#include <metric/numeric/math/typetraits/IsSVDExpr.h>
#include <metric/numeric/math/typetraits/IsScalar.h>
#include <metric/numeric/math/typetraits/IsSchurExpr.h>
#include <metric/numeric/math/typetraits/IsSerialExpr.h>
#include <metric/numeric/math/typetraits/IsShrinkable.h>
#include <metric/numeric/math/typetraits/IsSolveExpr.h>
#include <metric/numeric/math/typetraits/IsSparseElement.h>
#include <metric/numeric/math/typetraits/IsSparseMatrix.h>
#include <metric/numeric/math/typetraits/IsSparseVector.h>
#include <metric/numeric/math/typetraits/IsSquare.h>
#include <metric/numeric/math/typetraits/IsStatic.h>
#include <metric/numeric/math/typetraits/IsStrictlyLower.h>
#include <metric/numeric/math/typetraits/IsStrictlyTriangular.h>
#include <metric/numeric/math/typetraits/IsStrictlyUpper.h>
#include <metric/numeric/math/typetraits/IsSubExpr.h>
#include <metric/numeric/math/typetraits/IsSubmatrix.h>
#include <metric/numeric/math/typetraits/IsSubvector.h>
#include <metric/numeric/math/typetraits/IsSymmetric.h>
#include <metric/numeric/math/typetraits/IsTVecMatMultExpr.h>
#include <metric/numeric/math/typetraits/IsTemporary.h>
#include <metric/numeric/math/typetraits/IsTransExpr.h>
#include <metric/numeric/math/typetraits/IsTransformation.h>
#include <metric/numeric/math/typetraits/IsTriangular.h>
#include <metric/numeric/math/typetraits/IsUnaryMapExpr.h>
#include <metric/numeric/math/typetraits/IsUniLower.h>
#include <metric/numeric/math/typetraits/IsUniTriangular.h>
#include <metric/numeric/math/typetraits/IsUniUpper.h>
#include <metric/numeric/math/typetraits/IsUniform.h>
#include <metric/numeric/math/typetraits/IsUpper.h>
#include <metric/numeric/math/typetraits/IsVecEvalExpr.h>
#include <metric/numeric/math/typetraits/IsVecExpandExpr.h>
#include <metric/numeric/math/typetraits/IsVecGenExpr.h>
#include <metric/numeric/math/typetraits/IsVecMapExpr.h>
#include <metric/numeric/math/typetraits/IsVecNoAliasExpr.h>
#include <metric/numeric/math/typetraits/IsVecNoSIMDExpr.h>
#include <metric/numeric/math/typetraits/IsVecRepeatExpr.h>
#include <metric/numeric/math/typetraits/IsVecScalarDivExpr.h>
#include <metric/numeric/math/typetraits/IsVecScalarMultExpr.h>
#include <metric/numeric/math/typetraits/IsVecSerialExpr.h>
#include <metric/numeric/math/typetraits/IsVecTVecMapExpr.h>
#include <metric/numeric/math/typetraits/IsVecTVecMultExpr.h>
#include <metric/numeric/math/typetraits/IsVecTransExpr.h>
#include <metric/numeric/math/typetraits/IsVecVecAddExpr.h>
#include <metric/numeric/math/typetraits/IsVecVecDivExpr.h>
#include <metric/numeric/math/typetraits/IsVecVecKronExpr.h>
#include <metric/numeric/math/typetraits/IsVecVecMapExpr.h>
#include <metric/numeric/math/typetraits/IsVecVecMultExpr.h>
#include <metric/numeric/math/typetraits/IsVecVecSubExpr.h>
#include <metric/numeric/math/typetraits/IsVector.h>
#include <metric/numeric/math/typetraits/IsView.h>
#include <metric/numeric/math/typetraits/IsZero.h>
#include <metric/numeric/math/typetraits/LowType.h>
#include <metric/numeric/math/typetraits/MakeComplex.h>
#include <metric/numeric/math/typetraits/MaxSize.h>
#include <metric/numeric/math/typetraits/RemoveAdaptor.h>
#include <metric/numeric/math/typetraits/RequiresEvaluation.h>
#include <metric/numeric/math/typetraits/Size.h>
#include <metric/numeric/math/typetraits/StorageOrder.h>
#include <metric/numeric/math/typetraits/TransposeFlag.h>
#include <metric/numeric/math/typetraits/UnderlyingBuiltin.h>
#include <metric/numeric/math/typetraits/UnderlyingElement.h>
#include <metric/numeric/math/typetraits/UnderlyingNumeric.h>
#include <metric/numeric/math/typetraits/UnderlyingScalar.h>
#include <metric/numeric/math/typetraits/YieldsDiagonal.h>
#include <metric/numeric/math/typetraits/YieldsHermitian.h>
#include <metric/numeric/math/typetraits/YieldsIdentity.h>
#include <metric/numeric/math/typetraits/YieldsLower.h>
#include <metric/numeric/math/typetraits/YieldsStrictlyLower.h>
#include <metric/numeric/math/typetraits/YieldsStrictlyTriangular.h>
#include <metric/numeric/math/typetraits/YieldsStrictlyUpper.h>
#include <metric/numeric/math/typetraits/YieldsSymmetric.h>
#include <metric/numeric/math/typetraits/YieldsTriangular.h>
#include <metric/numeric/math/typetraits/YieldsUniLower.h>
#include <metric/numeric/math/typetraits/YieldsUniTriangular.h>
#include <metric/numeric/math/typetraits/YieldsUniUpper.h>
#include <metric/numeric/math/typetraits/YieldsUniform.h>
#include <metric/numeric/math/typetraits/YieldsUpper.h>
#include <metric/numeric/math/typetraits/YieldsZero.h>

#endif
