name: Benchmark
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/benchmark.yml'
      - '3rdparty/**'
      - 'benchmarks/**'
      - 'modules/**'
      - 'CMakeLists.txt'
      - 'metric.hpp'
jobs:
  benchmark:
    name: Performance check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache apt
        uses: actions/cache@v2
        env:
          cache-name: cache-apt
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Cache ccache
        uses: actions/cache@v2
        env:
          cache-name: cache-ccache
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-benchmark-${{ env.cache-name }}

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install cmake
          sudo apt-get install libopenblas-dev
          sudo apt-get install libjpeg-dev
          sudo apt-get install nlohmann-json3-dev
          git clone https://bitbucket.org/blaze-lib/blaze.git --depth=1 --branch=v3.8 && cd blaze && cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ . && sudo make install
          git clone https://github.com/USCiLab/cereal --depth=1 --branch=v1.3.0 && cd cereal && cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ -DJUST_INSTALL_CEREAL=ON . && sudo make install
          sudo apt-get install -y g++-9 g++-9-multilib
          sudo apt-get install ccache
          echo "CC=gcc-9" >> $GITHUB_ENV
          echo "CXX=g++-9" >> $GITHUB_ENV

      - name: Build benchmark
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --target convolution_benchmarks

      - name: Run benchmark
        run: |
          ./build/benchmarks/image_processing_benchmarks/convolution_benchmarks --benchmark-samples 10 --out convolution-benchmark-output

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Convolution
          tool: 'catch2'
          output-file-path: convolution-benchmark-output
          # Personal access token to deploy GitHub Pages branch
          github-token: ${{ secrets.CONTINIOUS_BENCHMARK_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true